/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50617
Source Host           : localhost:3306
Source Database       : detoxthai_lte

Target Server Type    : MYSQL
Target Server Version : 50617
File Encoding         : 65001

Date: 2015-06-05 19:15:41
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for tbl_prename
-- ----------------------------
DROP TABLE IF EXISTS `tbl_prename`;
CREATE TABLE `tbl_prename` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `pre_name1` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  `pre_name2` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=504 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of tbl_prename
-- ----------------------------
INSERT INTO `tbl_prename` VALUES ('1', 'ด.ช.', 'เด็กชาย');
INSERT INTO `tbl_prename` VALUES ('2', 'ด.ญ.', 'เด็กหญิง');
INSERT INTO `tbl_prename` VALUES ('3', 'นาย', 'นาย');
INSERT INTO `tbl_prename` VALUES ('4', 'น.ส.', 'นางสาว');
INSERT INTO `tbl_prename` VALUES ('5', 'นาง', 'นาง');
INSERT INTO `tbl_prename` VALUES ('6', 'น.ช.ม.ล.', 'นักโทษชายหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('7', 'น.ช.', 'นักโทษชาย');
INSERT INTO `tbl_prename` VALUES ('8', 'น.ญ.', 'นักโทษหญิง');
INSERT INTO `tbl_prename` VALUES ('9', 'น.ช.จ.ส.อ.', 'นักโทษชายจ่าสิบเอก');
INSERT INTO `tbl_prename` VALUES ('10', 'น.ช.พลฯ.', 'นักโทษชายพลทหาร');
INSERT INTO `tbl_prename` VALUES ('11', 'น.ช.ร.ต.', 'นักโทษชายร้อยตรี');
INSERT INTO `tbl_prename` VALUES ('12', 'พระเจ้าหลานเธอ พระองค์เจ้า', 'พระเจ้าหลานเธอ พระองค์เจ้า');
INSERT INTO `tbl_prename` VALUES ('13', 'พระบาทสมเด็จพระเจ้าอยู่หัว', 'พระบาทสมเด็จพระเจ้าอยู่หัว');
INSERT INTO `tbl_prename` VALUES ('14', 'สมเด็จพระนางเจ้า', 'สมเด็จพระนางเจ้า');
INSERT INTO `tbl_prename` VALUES ('15', 'สมเด็จพระศรีนครินทราบรมราชชนนี', 'สมเด็จพระศรีนครินทราบรมราชชนนี');
INSERT INTO `tbl_prename` VALUES ('16', 'พลโทสมเด็จพระบรมโอรสาธิราช', 'พลโทสมเด็จพระบรมโอรสาธิราช');
INSERT INTO `tbl_prename` VALUES ('17', 'พลตรีสมเด็จพระเทพรัตนราชสุดา', 'พลตรีสมเด็จพระเทพรัตนราชสุดา');
INSERT INTO `tbl_prename` VALUES ('18', 'พระเจ้าวรวงศ์เธอพระองค์หญิง', 'พระเจ้าวรวงศ์เธอพระองค์หญิง');
INSERT INTO `tbl_prename` VALUES ('19', 'พระเจ้าวรวงศ์เธอ พระองค์เจ้า', 'พระเจ้าวรวงศ์เธอ พระองค์เจ้า');
INSERT INTO `tbl_prename` VALUES ('20', 'สมเด็จพระราชชนนี', 'สมเด็จพระราชชนนี');
INSERT INTO `tbl_prename` VALUES ('21', 'สมเด็จพระเจ้าพี่นางเธอเจ้าฟ้า', 'สมเด็จพระเจ้าพี่นางเธอเจ้าฟ้า');
INSERT INTO `tbl_prename` VALUES ('22', 'สมเด็จพระ', 'สมเด็จพระ');
INSERT INTO `tbl_prename` VALUES ('23', 'สมเด็จพระเจ้าลูกเธอ', 'สมเด็จพระเจ้าลูกเธอ');
INSERT INTO `tbl_prename` VALUES ('24', 'สมเด็จพระเจ้าลูกยาเธอ', 'สมเด็จพระเจ้าลูกยาเธอ');
INSERT INTO `tbl_prename` VALUES ('25', 'สมเด็จเจ้าฟ้า', 'สมเด็จเจ้าฟ้า');
INSERT INTO `tbl_prename` VALUES ('26', 'พระเจ้าบรมวงศ์เธอ', 'พระเจ้าบรมวงศ์เธอ');
INSERT INTO `tbl_prename` VALUES ('27', 'พระเจ้าวรวงศ์เธอ', 'พระเจ้าวรวงศ์เธอ');
INSERT INTO `tbl_prename` VALUES ('28', 'พระเจ้าหลานเธอ', 'พระเจ้าหลานเธอ');
INSERT INTO `tbl_prename` VALUES ('29', 'พระเจ้าหลานยาเธอ', 'พระเจ้าหลานยาเธอ');
INSERT INTO `tbl_prename` VALUES ('30', 'พระวรวงศ์เธอ', 'พระวรวงศ์เธอ');
INSERT INTO `tbl_prename` VALUES ('31', 'สมเด็จพระเจ้าภคินีเธอ', 'สมเด็จพระเจ้าภคินีเธอ');
INSERT INTO `tbl_prename` VALUES ('32', 'พระองค์เจ้า', 'พระองค์เจ้า');
INSERT INTO `tbl_prename` VALUES ('33', 'ม.จ.', 'หม่อมเจ้า');
INSERT INTO `tbl_prename` VALUES ('34', 'ม.ร.ว.', 'หม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('35', 'ม.ล.', 'หม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('36', 'พระยา', 'พระยา');
INSERT INTO `tbl_prename` VALUES ('37', 'หลวง', 'หลวง');
INSERT INTO `tbl_prename` VALUES ('38', 'ขุน', 'ขุน');
INSERT INTO `tbl_prename` VALUES ('39', 'หมื่น', 'หมื่น');
INSERT INTO `tbl_prename` VALUES ('40', 'เจ้าคุณ', 'เจ้าคุณ');
INSERT INTO `tbl_prename` VALUES ('41', 'พระวรวงศ์เธอพระองค์เจ้า', 'พระวรวงศ์เธอพระองค์เจ้า');
INSERT INTO `tbl_prename` VALUES ('42', 'คุณ', 'คุณ');
INSERT INTO `tbl_prename` VALUES ('43', 'คุณหญิง', 'คุณหญิง');
INSERT INTO `tbl_prename` VALUES ('44', 'ท่านผู้หญิง ม.ล.', 'ท่านผู้หญิงหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('45', 'ศจ.น.พ.', 'ศาสตราจารย์นายแพทย์');
INSERT INTO `tbl_prename` VALUES ('46', 'พ.ญ.คุณหญิง', 'แพทย์หญิงคุณหญิง');
INSERT INTO `tbl_prename` VALUES ('47', 'น.พ.', 'นายแพทย์');
INSERT INTO `tbl_prename` VALUES ('48', 'พ.ญ.', 'แพทย์หญิง');
INSERT INTO `tbl_prename` VALUES ('49', 'ท.พ.', 'ทัณตแพทย์');
INSERT INTO `tbl_prename` VALUES ('50', 'ท.ญ.', 'ทัณตแพทย์หญิง');
INSERT INTO `tbl_prename` VALUES ('51', 'สพ.', 'สัตวแพทย์');
INSERT INTO `tbl_prename` VALUES ('52', 'สญ.', 'สัตวแพทย์หญิง');
INSERT INTO `tbl_prename` VALUES ('53', 'ดร.', 'ดอกเตอร์');
INSERT INTO `tbl_prename` VALUES ('54', 'ผศ.', 'ผู้ช่วยศาสตราจารย์');
INSERT INTO `tbl_prename` VALUES ('55', 'รศ.', 'รองศาสตราจารย์');
INSERT INTO `tbl_prename` VALUES ('56', 'ศจ.', 'ศาสตราจารย์');
INSERT INTO `tbl_prename` VALUES ('57', 'ภก.', 'เภสัชกรชาย');
INSERT INTO `tbl_prename` VALUES ('58', 'ภญ.', 'เภสัชกรหญิง');
INSERT INTO `tbl_prename` VALUES ('59', 'หม่อม', 'หม่อม');
INSERT INTO `tbl_prename` VALUES ('60', 'รองอำมาตย์เอก', 'รองอำมาตย์เอก');
INSERT INTO `tbl_prename` VALUES ('61', 'ท้าว', 'ท้าว');
INSERT INTO `tbl_prename` VALUES ('62', 'เจ้า', 'เจ้า');
INSERT INTO `tbl_prename` VALUES ('63', 'ท่านผู้หญิง', 'ท่านผู้หญิง');
INSERT INTO `tbl_prename` VALUES ('64', 'คุณพระ', 'คุณพระ');
INSERT INTO `tbl_prename` VALUES ('65', 'ศจ.คุณหญิง', 'ศาสตราจารย์คุณหญิง');
INSERT INTO `tbl_prename` VALUES ('66', 'ซิสเตอร์', 'ซิสเตอร์');
INSERT INTO `tbl_prename` VALUES ('67', 'เจ้าชาย', 'เจ้าชาย');
INSERT INTO `tbl_prename` VALUES ('68', 'เจ้าหญิง', 'เจ้าหญิง');
INSERT INTO `tbl_prename` VALUES ('69', 'รองเสวกตรี', 'รองเสวกตรี');
INSERT INTO `tbl_prename` VALUES ('70', 'เสด็จเจ้า', 'เสด็จเจ้า');
INSERT INTO `tbl_prename` VALUES ('71', 'เอกอัครราชฑูต', 'เอกอัครราชฑูต');
INSERT INTO `tbl_prename` VALUES ('72', 'พลสารวัตร', 'พลสารวัตร');
INSERT INTO `tbl_prename` VALUES ('73', 'สมเด็จเจ้า', 'สมเด็จเจ้า');
INSERT INTO `tbl_prename` VALUES ('74', 'เจ้าฟ้า', 'เจ้าฟ้า');
INSERT INTO `tbl_prename` VALUES ('75', 'รองอำมาตย์ตรี', 'รองอำมาตย์ตรี');
INSERT INTO `tbl_prename` VALUES ('76', 'ม.จ.หญิง', 'หม่อมเจ้าหญิง');
INSERT INTO `tbl_prename` VALUES ('77', 'ทูลกระหม่อม', 'ทูลกระหม่อม');
INSERT INTO `tbl_prename` VALUES ('78', 'ศ.ดร.', 'ศาสตราจารย์ดอกเตอร์');
INSERT INTO `tbl_prename` VALUES ('79', 'เจ้านาง', 'เจ้านาง');
INSERT INTO `tbl_prename` VALUES ('80', 'จ่าสำรอง', 'จ่าสำรอง');
INSERT INTO `tbl_prename` VALUES ('81', 'พล.อ.', 'พลเอก');
INSERT INTO `tbl_prename` VALUES ('82', 'ว่าที่ พล.อ.', 'ว่าที่พลเอก');
INSERT INTO `tbl_prename` VALUES ('83', 'พล.ท.', 'พลโท');
INSERT INTO `tbl_prename` VALUES ('84', 'พล.ต.', 'พลตรี');
INSERT INTO `tbl_prename` VALUES ('85', 'ว่าที่ พล.ต.', 'ว่าที่พลตรี');
INSERT INTO `tbl_prename` VALUES ('86', 'พ.อ.(พิเศษ)', 'พันเอกพิเศษ');
INSERT INTO `tbl_prename` VALUES ('87', 'ว่าที่ พ.อ.(พิเศษ)', 'ว่าที่พันเอกพิเศษ');
INSERT INTO `tbl_prename` VALUES ('88', 'พ.อ.', 'พันเอก');
INSERT INTO `tbl_prename` VALUES ('89', 'ว่าที่ พ.อ.', 'ว่าที่พันเอก');
INSERT INTO `tbl_prename` VALUES ('90', 'พ.ท.', 'พันโท');
INSERT INTO `tbl_prename` VALUES ('91', 'ว่าที่ พ.ท.', 'ว่าที่พันโท');
INSERT INTO `tbl_prename` VALUES ('92', 'พ.ต.', 'พันตรี');
INSERT INTO `tbl_prename` VALUES ('93', 'ว่าที่ พ.ต.', 'ว่าที่พันตรี');
INSERT INTO `tbl_prename` VALUES ('94', 'ร.อ.', 'ร้อยเอก');
INSERT INTO `tbl_prename` VALUES ('95', 'ว่าที่ ร.อ.', 'ว่าที่ร้อยเอก');
INSERT INTO `tbl_prename` VALUES ('96', 'ร.ท.', 'ร้อยโท');
INSERT INTO `tbl_prename` VALUES ('97', 'ว่าที่ ร.ท.', 'ว่าที่ร้อยโท');
INSERT INTO `tbl_prename` VALUES ('98', 'ร.ต.', 'ร้อยตรี');
INSERT INTO `tbl_prename` VALUES ('99', 'ว่าที่ ร.ต.', 'ว่าที่ร้อยตรี');
INSERT INTO `tbl_prename` VALUES ('100', 'จ.ส.อ.', 'จ่าสิบเอก');
INSERT INTO `tbl_prename` VALUES ('101', 'จ.ส.ท.', 'จ่าสิบโท');
INSERT INTO `tbl_prename` VALUES ('102', 'จ.ส.ต.', 'จ่าสิบตรี');
INSERT INTO `tbl_prename` VALUES ('103', 'ส.อ.', 'สิบเอก');
INSERT INTO `tbl_prename` VALUES ('104', 'ส.ท.', 'สิบโท');
INSERT INTO `tbl_prename` VALUES ('105', 'ส.ต.', 'สิบตรี');
INSERT INTO `tbl_prename` VALUES ('106', 'พลฯ', 'พลทหาร');
INSERT INTO `tbl_prename` VALUES ('107', 'นนร.', 'นักเรียนนายร้อย');
INSERT INTO `tbl_prename` VALUES ('108', 'นนส.', 'นักเรียนนายสิบ');
INSERT INTO `tbl_prename` VALUES ('109', 'พล.จ.', 'พลจัตวา');
INSERT INTO `tbl_prename` VALUES ('110', 'พลฯ อาสา', 'พลฯ อาสาสมัคร');
INSERT INTO `tbl_prename` VALUES ('111', 'ร.อ.ม.จ.', 'ร้อยเอกหม่อมเจ้า');
INSERT INTO `tbl_prename` VALUES ('112', 'พล.ท.ม.จ.', 'พลโทหม่อมเจ้า');
INSERT INTO `tbl_prename` VALUES ('113', 'ร.ต.ม.จ.', 'ร้อยตรีหม่อมเจ้า');
INSERT INTO `tbl_prename` VALUES ('114', 'ร.ท.ม.จ.', 'ร้อยโทหม่อมเจ้า');
INSERT INTO `tbl_prename` VALUES ('115', 'พ.ท.ม.จ.', 'พันโทหม่อมเจ้า');
INSERT INTO `tbl_prename` VALUES ('116', 'พ.อ.ม.จ.', 'พันเอกหม่อมเจ้า');
INSERT INTO `tbl_prename` VALUES ('117', 'พ.ต.ม.ร.ว.', 'พันตรีหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('118', 'พ.ท.ม.ร.ว.', 'พันโทหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('119', 'ส.ต.ม.ร.ว.', 'สิบตรีหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('120', 'พ.อ.ม.ร.ว.', 'พันเอกหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('121', 'จ.ส.อ.ม.ร.ว.', 'จ่าสิบเอกหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('122', 'ร.อ.ม.ร.ว.', 'ร้อยเอกหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('123', 'ร.ต.ม.ร.ว.', 'ร้อยตรีหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('124', 'ส.อ.ม.ร.ว.', 'สิบเอกหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('125', 'ร.ท.ม.ร.ว.', 'ร้อยโทหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('126', 'พ.อ.(พิเศษ)ม.ร.ว.', 'พันเอก(พิเศษ)หม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('127', 'พลฯม.ล.', 'พลฯหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('128', 'ร.อ.ม.ล.', 'ร้อยเอกหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('129', 'ส.ท.ม.ล.', 'สิบโทหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('130', 'พล.ท.ม.ล.', 'พลโทหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('131', 'ร.ท.ม.ล.', 'ร้อยโทหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('132', 'ร.ต.ม.ล.', 'ร้อยตรีหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('133', 'ส.อ.ม.ล.', 'สิบเอกหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('134', 'พล.ต.ม.ล.', 'พลตรีหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('135', 'พ.ต.ม.ล.', 'พันตรีหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('136', 'พ.อ.ม.ล.', 'พันเอกหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('137', 'พ.ท.ม.ล.', 'พันโทหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('138', 'จ.ส.ต.ม.ล.', 'จ่าสิบตรีหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('139', 'นนร.ม.ล.', 'นักเรียนนายร้อยหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('140', 'ว่าที่ร.ต.ม.ล.', 'ว่าที่ร้อยตรีหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('141', 'จ.ส.อ.ม.ล.', 'จ่าสิบเอกหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('142', 'ร.อ.น.พ.', 'ร้อยเอกนายแพทย์');
INSERT INTO `tbl_prename` VALUES ('143', 'ร.อ.พ.ญ.', 'ร้อยเอกแพทย์หญิง');
INSERT INTO `tbl_prename` VALUES ('144', 'ร.ท.น.พ.', 'ร้อยโทนายแพทย์');
INSERT INTO `tbl_prename` VALUES ('145', 'พ.ต.น.พ.', 'พันตรีนายแพทย์');
INSERT INTO `tbl_prename` VALUES ('146', 'ว่าที่ ร.ท.น.พ.', 'ว่าที่ร้อยโทนายแพทย์');
INSERT INTO `tbl_prename` VALUES ('147', 'พ.อ.น.พ.', 'พันเอกนายแพทย์');
INSERT INTO `tbl_prename` VALUES ('148', 'ร.ต.น.พ.', 'ร้อยตรีนายแพทย์');
INSERT INTO `tbl_prename` VALUES ('149', 'ร.ท.พ.ญ.', 'ร้อยโทแพทย์หญิง');
INSERT INTO `tbl_prename` VALUES ('150', 'พล.ต.น.พ.', 'พลตรีนายแพทย์');
INSERT INTO `tbl_prename` VALUES ('151', 'พ.ท.น.พ.', 'พันโทนายแพทย์');
INSERT INTO `tbl_prename` VALUES ('152', 'จอมพล', 'จอมพล');
INSERT INTO `tbl_prename` VALUES ('153', 'พ.ท.หลวง', 'พันโทหลวง');
INSERT INTO `tbl_prename` VALUES ('154', 'พ.ต.พระเจ้าวรวงศ์เธอพระองค์เจ้า', 'พันตรีพระเจ้าวรวงศ์เธอพระองค์เจ้า');
INSERT INTO `tbl_prename` VALUES ('155', 'ศจ.พ.อ.', 'ศาสตราจารย์พันเอก');
INSERT INTO `tbl_prename` VALUES ('156', 'พ.ต.หลวง', 'พันตรีหลวง');
INSERT INTO `tbl_prename` VALUES ('157', 'พล.ท.หลวง', 'พลโทหลวง');
INSERT INTO `tbl_prename` VALUES ('158', 'ร.ท.ดร.', 'ร้อยโทดอกเตอร์');
INSERT INTO `tbl_prename` VALUES ('159', 'ร.อ.ดร.', 'ร้อยเอกดอกเตอร์');
INSERT INTO `tbl_prename` VALUES ('160', 'ส.ห.', 'สารวัตรทหาร');
INSERT INTO `tbl_prename` VALUES ('161', 'ร.ต.ดร.', 'ร้อยตรีดอกเตอร์');
INSERT INTO `tbl_prename` VALUES ('162', 'พ.ต.คุณหญิง', 'พันตรีคุณหญิง');
INSERT INTO `tbl_prename` VALUES ('163', 'จ.ส.ต.ม.ร.ว.', 'จ่าสิบตรีหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('164', 'พล.จ.หลวง', 'พลจัตวาหลวง');
INSERT INTO `tbl_prename` VALUES ('165', 'พล.ต.ม.ร.ว.', 'พลตรีหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('166', 'พ.ต.พระเจ้าวรวงศ์เธอพระองค์', 'พันตรีพระเจ้าวรวงศ์เธอพระองค์');
INSERT INTO `tbl_prename` VALUES ('167', 'ท่านผู้หญิง ม.ร.ว.', 'ท่านผู้หญิงหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('168', 'ศจ.ร.อ.', 'ศาสตราจารย์ร้อยเอก');
INSERT INTO `tbl_prename` VALUES ('169', 'พ.ท.คุณหญิง', 'พันโทคุณหญิง');
INSERT INTO `tbl_prename` VALUES ('170', 'ร.ต.พ.ญ.', 'ร้อยตรีแพทย์หญิง');
INSERT INTO `tbl_prename` VALUES ('171', 'พล.อ.มล.', 'พลเอกหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('172', 'ว่าที่ ร.ต.ม.ร.ว.', 'ว่าที่ร้อยตรีหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('173', 'พ.อ.หญิง คุณหญิง', 'พันเอกหญิงคุณหญิง');
INSERT INTO `tbl_prename` VALUES ('174', 'จ.ส.อ.พิเศษ', 'จ่าสิบเอกพิเศษ');
INSERT INTO `tbl_prename` VALUES ('175', 'พล.ร.อ.', 'พลเรือเอก');
INSERT INTO `tbl_prename` VALUES ('176', 'ว่าที่ พล.ร.อ.', 'ว่าที่พลเรือเอก');
INSERT INTO `tbl_prename` VALUES ('177', 'พล.ร.ท.', 'พลเรือโท');
INSERT INTO `tbl_prename` VALUES ('178', 'ว่าที่ พล.ร.ท.', 'ว่าที่พลเรือโท');
INSERT INTO `tbl_prename` VALUES ('179', 'พล.ร.ต.', 'พลเรือตรี');
INSERT INTO `tbl_prename` VALUES ('180', 'ว่าที่ พล.ร.ต.', 'ว่าที่พลเรือตรี');
INSERT INTO `tbl_prename` VALUES ('181', 'น.อ.พิเศษ', 'นาวาเอกพิเศษ');
INSERT INTO `tbl_prename` VALUES ('182', 'ว่าที่ น.อ.พิเศษ', 'ว่าที่นาวาเอกพิเศษ');
INSERT INTO `tbl_prename` VALUES ('183', 'น.อ.', 'นาวาเอก');
INSERT INTO `tbl_prename` VALUES ('184', 'ว่าที่ น.อ.', 'ว่าที่นาวาเอก');
INSERT INTO `tbl_prename` VALUES ('185', 'น.ท.', 'นาวาโท');
INSERT INTO `tbl_prename` VALUES ('186', 'ว่าที่ น.ท.', 'ว่าที่นาวาโท');
INSERT INTO `tbl_prename` VALUES ('187', 'น.ต.', 'นาวาตรี');
INSERT INTO `tbl_prename` VALUES ('188', 'ว่าที่ น.ต.', 'ว่าที่นาวาตรี');
INSERT INTO `tbl_prename` VALUES ('189', 'ร.อ.', 'เรือเอก');
INSERT INTO `tbl_prename` VALUES ('190', 'ว่าที่ ร.อ.', 'ว่าที่เรือเอก');
INSERT INTO `tbl_prename` VALUES ('191', 'ร.ท.', 'เรือโท');
INSERT INTO `tbl_prename` VALUES ('192', 'ว่าที่ ร.ท.', 'ว่าที่เรือโท');
INSERT INTO `tbl_prename` VALUES ('193', 'ร.ต.', 'เรือตรี');
INSERT INTO `tbl_prename` VALUES ('194', 'ว่าที่ ร.ต.', 'ว่าที่เรือตรี');
INSERT INTO `tbl_prename` VALUES ('195', 'พ.จ.อ.', 'พันจ่าเอก');
INSERT INTO `tbl_prename` VALUES ('196', 'พ.จ.ท.', 'พันจ่าโท');
INSERT INTO `tbl_prename` VALUES ('197', 'พ.จ.ต.', 'พันจ่าตรี');
INSERT INTO `tbl_prename` VALUES ('198', 'จ.อ.', 'จ่าเอก');
INSERT INTO `tbl_prename` VALUES ('199', 'จ.ท.', 'จ่าโท');
INSERT INTO `tbl_prename` VALUES ('200', 'จ.ต.', 'จ่าตรี');
INSERT INTO `tbl_prename` VALUES ('201', 'พลฯ', 'พลฯทหารเรือ');
INSERT INTO `tbl_prename` VALUES ('202', 'นนร.', 'นักเรียนนายเรือ');
INSERT INTO `tbl_prename` VALUES ('203', 'นรจ.', 'นักเรียนจ่าทหารเรือ');
INSERT INTO `tbl_prename` VALUES ('204', 'พล.ร.จ.', 'พลเรือจัตวา');
INSERT INTO `tbl_prename` VALUES ('205', 'น.ท.ม.จ.', 'นาวาโทหม่อมเจ้า');
INSERT INTO `tbl_prename` VALUES ('206', 'น.อ.ม.จ.', 'นาวาเอกหม่อมเจ้า');
INSERT INTO `tbl_prename` VALUES ('207', 'น.ต.ม.จ.', 'นาวาตรีหม่อมเจ้า');
INSERT INTO `tbl_prename` VALUES ('208', 'พล.ร.ต.ม.ร.ว.', 'พลเรือตรีหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('209', 'น.อ.ม.ร.ว.', 'นาวาเอกหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('210', 'น.ท.ม.ร.ว.', 'นาวาโทหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('211', 'น.ต.ม.ร.ว.', 'นาวาตรีหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('212', 'น.ท.ม.ล.', 'นาวาโทหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('213', 'น.ต.ม.ล.', 'นาวาตรีหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('214', 'พ.จ.อ.ม.ล.', 'พันจ่าเอกหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('215', 'น.ต.พ.ญ.', 'นาวาตรีแพทย์หญิง');
INSERT INTO `tbl_prename` VALUES ('216', 'น.อ.หลวง', 'นาวาอากาศเอกหลวง');
INSERT INTO `tbl_prename` VALUES ('217', 'พล.ร.ต.ม.จ.', 'พลเรือตรีหม่อมเจ้า');
INSERT INTO `tbl_prename` VALUES ('218', 'น.ต.น.พ.', 'นาวาตรีนายแพทย์');
INSERT INTO `tbl_prename` VALUES ('219', 'พล.ร.ต.ม.ล.', 'พลเรือตรีหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('220', 'พล.อ.อ.', 'พลอากาศเอก');
INSERT INTO `tbl_prename` VALUES ('221', 'ว่าที่ พล.อ.อ.', 'ว่าที่พลอากาศเอก');
INSERT INTO `tbl_prename` VALUES ('222', 'พล.อ.ท.', 'พลอากาศโท');
INSERT INTO `tbl_prename` VALUES ('223', 'ว่าที่ พล.อ.ท.', 'ว่าที่พลอากาศโท');
INSERT INTO `tbl_prename` VALUES ('224', 'พล.อ.ต.', 'พลอากาศตรี');
INSERT INTO `tbl_prename` VALUES ('225', 'ว่าที่ พล.อ.ต.', 'ว่าที่พลอากาศตรี');
INSERT INTO `tbl_prename` VALUES ('226', 'น.อ.พิเศษ', 'นาวาอากาศเอกพิเศษ');
INSERT INTO `tbl_prename` VALUES ('227', 'ว่าที่ น.อ.พิเศษ', 'ว่าที่นาวาอากาศเอกพิเศษ');
INSERT INTO `tbl_prename` VALUES ('228', 'น.อ.', 'นาวาอากาศเอก');
INSERT INTO `tbl_prename` VALUES ('229', 'ว่าที่ น.อ.', 'ว่าที่นาวาอากาศเอก');
INSERT INTO `tbl_prename` VALUES ('230', 'น.ท.', 'นาวาอากาศโท');
INSERT INTO `tbl_prename` VALUES ('231', 'ว่าที่ น.ท.', 'ว่าที่นาวาอากาศโท');
INSERT INTO `tbl_prename` VALUES ('232', 'น.ต.', 'นาวาอากาศตรี');
INSERT INTO `tbl_prename` VALUES ('233', 'ว่าที่ น.ต.', 'ว่าที่นาวาอากาศตรี');
INSERT INTO `tbl_prename` VALUES ('234', 'ร.อ.', 'เรืออากาศเอก');
INSERT INTO `tbl_prename` VALUES ('235', 'ว่าที่ ร.อ.', 'ว่าที่เรืออากาศเอก');
INSERT INTO `tbl_prename` VALUES ('236', 'ร.ท.', 'เรืออากาศโท');
INSERT INTO `tbl_prename` VALUES ('237', 'ว่าที่ ร.ท.', 'ว่าที่เรืออากาศโท');
INSERT INTO `tbl_prename` VALUES ('238', 'ร.ต.', 'เรืออากาศตรี');
INSERT INTO `tbl_prename` VALUES ('239', 'ว่าที่ ร.ต.', 'ว่าที่เรืออากาศตรี');
INSERT INTO `tbl_prename` VALUES ('240', 'พ.อ.อ.', 'พันจ่าอากาศเอก');
INSERT INTO `tbl_prename` VALUES ('241', 'พ.อ.ท.', 'พันจ่าอากาศโท');
INSERT INTO `tbl_prename` VALUES ('242', 'พ.อ.ต.', 'พันจ่าอากาศตรี');
INSERT INTO `tbl_prename` VALUES ('243', 'จ.อ.', 'จ่าอากาศเอก');
INSERT INTO `tbl_prename` VALUES ('244', 'จ.ท.', 'จ่าอากาศโท');
INSERT INTO `tbl_prename` VALUES ('245', 'จ.ต.', 'จ่าอากาศตรี');
INSERT INTO `tbl_prename` VALUES ('246', 'พลฯ', 'พลฯทหารอากาศ');
INSERT INTO `tbl_prename` VALUES ('247', 'นนอ.', 'นักเรียนนายเรืออากาศ');
INSERT INTO `tbl_prename` VALUES ('248', 'นจอ.', 'นักเรียนจ่าอากาศ');
INSERT INTO `tbl_prename` VALUES ('249', 'น.พ.อ.', 'นักเรียนพยาบาลทหารอากาศ');
INSERT INTO `tbl_prename` VALUES ('250', 'พ.อ.อ.ม.ร.ว.', 'พันอากาศเอกหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('251', 'พล.อ.ต.ม.ร.ว.', 'พลอากาศตรีหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('252', 'พล.อ.ท.ม.ล.', 'พลอากาศโทหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('253', 'ร.ท.ขุน', 'เรืออากาศโทขุน');
INSERT INTO `tbl_prename` VALUES ('254', 'พ.อ.อ.ม.ล.', 'พันจ่าอากาศเอกหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('255', 'ร.อ.น.พ.', 'เรืออากาศเอกนายแพทย์');
INSERT INTO `tbl_prename` VALUES ('256', 'พล.อ.อ.ม.ร.ว.', 'พลอากาศเอกหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('257', 'พล.อ.ต.ม.ล.', 'พลอากาศตรีหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('258', 'พล.อ.จ.', 'พลอากาศจัตวา');
INSERT INTO `tbl_prename` VALUES ('259', 'พล.อ.ท.ม.ร.ว.', 'พลอากาศโทหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('260', 'น.อ.ม.ล.', 'นาวาอากาศเอกหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('261', 'พระครูพิบูลสมณธรรม', 'พระครูพิบูลสมณธรรม');
INSERT INTO `tbl_prename` VALUES ('262', 'พล.ต.อ.', 'พลตำรวจเอก');
INSERT INTO `tbl_prename` VALUES ('263', 'ว่าที่ พล.ต.อ.', 'ว่าที่พลตำรวจเอก');
INSERT INTO `tbl_prename` VALUES ('264', 'พล.ต.ท.', 'พลตำรวจโท');
INSERT INTO `tbl_prename` VALUES ('265', 'ว่าที่ พล.ต.ท.', 'ว่าที่พลตำรวจโท');
INSERT INTO `tbl_prename` VALUES ('266', 'พล.ต.ต.', 'พลตำรวจตรี');
INSERT INTO `tbl_prename` VALUES ('267', 'ว่าที่ พล.ต.ต.', 'ว่าที่พลตำรวจตรี');
INSERT INTO `tbl_prename` VALUES ('268', 'พล.ต.จ.', 'พลตำรวจจัตวา');
INSERT INTO `tbl_prename` VALUES ('269', 'ว่าที่พล.ต.จ.', 'ว่าที่พลตำรวจจัตวา');
INSERT INTO `tbl_prename` VALUES ('270', 'พ.ต.อ. (พิเศษ)', 'พันตำรวจเอก (พิเศษ)');
INSERT INTO `tbl_prename` VALUES ('271', 'ว่าที่ พ.ต.อ.พิเศษ', 'ว่าที่พันตำรวจเอก(พิเศษ)');
INSERT INTO `tbl_prename` VALUES ('272', 'พ.ต.อ.', 'พันตำรวจเอก');
INSERT INTO `tbl_prename` VALUES ('273', 'ว่าที่ พ.ต.อ.', 'ว่าที่พันตำรวจเอก');
INSERT INTO `tbl_prename` VALUES ('274', 'พ.ต.ท.', 'พันตำรวจโท');
INSERT INTO `tbl_prename` VALUES ('275', 'ว่าที่ พ.ต.ท.', 'ว่าที่พันตำรวจโท');
INSERT INTO `tbl_prename` VALUES ('276', 'พ.ต.ต.', 'พันตำรวจตรี');
INSERT INTO `tbl_prename` VALUES ('277', 'ว่าที่ พ.ต.ต.', 'ว่าที่พันตำรวจตรี');
INSERT INTO `tbl_prename` VALUES ('278', 'ร.ต.อ.', 'ร้อยตำรวจเอก');
INSERT INTO `tbl_prename` VALUES ('279', 'ว่าที่ ร.ต.อ.', 'ว่าที่ร้อยตำรวจเอก');
INSERT INTO `tbl_prename` VALUES ('280', 'ร.ต.ท.', 'ร้อยตำรวจโท');
INSERT INTO `tbl_prename` VALUES ('281', 'ว่าที่ ร.ต.ท.', 'ว่าที่ร้อยตำรวจโท');
INSERT INTO `tbl_prename` VALUES ('282', 'ร.ต.ต.', 'ร้อยตำรวจตรี');
INSERT INTO `tbl_prename` VALUES ('283', 'ว่าที่ ร.ต.ต.', 'ว่าที่ร้อยตำรวจตรี');
INSERT INTO `tbl_prename` VALUES ('284', 'ด.ต.', 'นายดาบตำรวจ');
INSERT INTO `tbl_prename` VALUES ('285', 'จ.ส.ต.', 'จ่าสิบตำรวจ');
INSERT INTO `tbl_prename` VALUES ('286', 'ส.ต.อ.', 'สิบตำรวจเอก');
INSERT INTO `tbl_prename` VALUES ('287', 'ส.ต.ท.', 'สิบตำรวจโท');
INSERT INTO `tbl_prename` VALUES ('288', 'ส.ต.ต.', 'สิบตำรวจตรี');
INSERT INTO `tbl_prename` VALUES ('289', 'นรต.', 'นักเรียนนายร้อยตำรวจ');
INSERT INTO `tbl_prename` VALUES ('290', 'นสต.', 'นักเรียนนายสิบตำรวจ');
INSERT INTO `tbl_prename` VALUES ('291', 'นพต.', 'นักเรียนพลตำรวจ');
INSERT INTO `tbl_prename` VALUES ('292', 'พลฯ', 'พลตำรวจ');
INSERT INTO `tbl_prename` VALUES ('293', 'พลฯพิเศษ', 'พลตำรวจพิเศษ');
INSERT INTO `tbl_prename` VALUES ('294', 'พลฯอาสา', 'พลตำรวจอาสาสมัคร');
INSERT INTO `tbl_prename` VALUES ('295', 'พลฯสำรอง', 'พลตำรวจสำรอง');
INSERT INTO `tbl_prename` VALUES ('296', 'พลฯสำรองพิเศษ', 'พลตำรวจสำรองพิเศษ');
INSERT INTO `tbl_prename` VALUES ('297', 'พลฯสมัคร', 'พลตำรวจสมัคร');
INSERT INTO `tbl_prename` VALUES ('298', 'อส.', 'สมาชิกอาสารักษาดินแดน');
INSERT INTO `tbl_prename` VALUES ('299', 'ก.ญ.', 'นายกองใหญ่');
INSERT INTO `tbl_prename` VALUES ('300', 'ก.อ.', 'นายกองเอก');
INSERT INTO `tbl_prename` VALUES ('301', 'ก.ท.', 'นายกองโท');
INSERT INTO `tbl_prename` VALUES ('302', 'ก.ต.', 'นายกองตรี');
INSERT INTO `tbl_prename` VALUES ('303', 'มว.อ.', 'นายหมวดเอก');
INSERT INTO `tbl_prename` VALUES ('304', 'มว.ท.', 'นายหมวดโท');
INSERT INTO `tbl_prename` VALUES ('305', 'มว.ต.', 'นายหมวดตรี');
INSERT INTO `tbl_prename` VALUES ('306', 'ม.ญ.', 'นายหมู่ใหญ่');
INSERT INTO `tbl_prename` VALUES ('307', 'ม.อ.', 'นายหมู่เอก');
INSERT INTO `tbl_prename` VALUES ('308', 'ม.ท.', 'นายหมู่โท');
INSERT INTO `tbl_prename` VALUES ('309', 'ม.ต.', 'นายหมู่ตรี');
INSERT INTO `tbl_prename` VALUES ('310', 'สมาชิกเอก', 'สมาชิกเอก');
INSERT INTO `tbl_prename` VALUES ('311', 'สมาชิกโท', 'สมาชิกโท');
INSERT INTO `tbl_prename` VALUES ('312', 'สมาชิกตรี', 'สมาชิกตรี');
INSERT INTO `tbl_prename` VALUES ('313', 'อส.ทพ.', 'อาสาสมัครทหารพราน');
INSERT INTO `tbl_prename` VALUES ('314', 'พ.ต.ท.ม.จ.', 'พันตำรวจโทหม่อมเจ้า');
INSERT INTO `tbl_prename` VALUES ('315', 'พ.ต.อ.ม.จ.', 'พันตำรวจเอกหม่อมเจ้า');
INSERT INTO `tbl_prename` VALUES ('316', 'นรต.ม.จ.', 'นักเรียนนายร้อยตำรวจหม่อมเจ้า');
INSERT INTO `tbl_prename` VALUES ('317', 'พล.ต.ต.ม.ร.ว.', 'พลตำรวจตรีหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('318', 'พ.ต.ต.ม.ร.ว.', 'พันตำรวจตรีหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('319', 'พ.ต.ท.ม.ร.ว.', 'พันตำรวจโทหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('320', 'พ.ต.อ.ม.ร.ว.', 'พันตำรวจเอกหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('321', 'ร.ต.อ.ม.ร.ว.', 'ร้อยตำรวจเอกหม่อมราชวงศ์');
INSERT INTO `tbl_prename` VALUES ('322', 'ส.ต.อ.ม.ล.', 'สิบตำรวจเอกหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('323', 'พ.ต.อ.ม.ล.', 'พันตำรวจเอกหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('324', 'พ.ต.ท.ม.ล.', 'พันตำรวจโทหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('325', 'นรต.ม.ล.', 'นักเรียนนายร้อยตำรวจหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('326', 'ร.ต.ท.ม.ล.', 'ร้อยตำรวจโทหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('327', 'ด.ต.ม.ล.', 'นายดาบตำรวจหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('328', 'พ.ต.ต.ม.ล.', 'พันตำรวจตรีหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('329', 'ศจ.น.พ.พ.ต.อ.', 'ศาสตราจารย์นายแพทย์พันตำรวจเอก');
INSERT INTO `tbl_prename` VALUES ('330', 'พ.ต.ท.น.พ.', 'พันตำรวจโทนายแพทย์');
INSERT INTO `tbl_prename` VALUES ('331', 'ร.ต.ท.น.พ.', 'ร้อยตำรวจโทนายแพทย์');
INSERT INTO `tbl_prename` VALUES ('332', 'ร.ต.อ.น.พ.', 'ร้อยตำรวจเอกนายแพทย์');
INSERT INTO `tbl_prename` VALUES ('333', 'พ.ต.ต.นพ.', 'พันตำรวจตรีนายแพทย์');
INSERT INTO `tbl_prename` VALUES ('334', 'พ.ต.อ.น.พ.', 'พันตำรวจเอกนายแพทย์');
INSERT INTO `tbl_prename` VALUES ('335', 'พ.ต.ต.หลวง', 'พันตำรวจตรีหลวง');
INSERT INTO `tbl_prename` VALUES ('336', 'ร.ต.ท.ดร.', 'ร้อยตำรวจโทดอกเตอร์');
INSERT INTO `tbl_prename` VALUES ('337', 'พ.ต.อ.ดร.', 'พันตำรวจเอกดอกเตอร์');
INSERT INTO `tbl_prename` VALUES ('338', 'ร.ต.อ.ม.ล.', 'ร้อยตำรวจเอกหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('339', 'พ.ต.อ.หญิง ท่านผู้หญิง', 'พันตำรวจเอกหญิง ท่านผู้หญิง');
INSERT INTO `tbl_prename` VALUES ('340', 'พล.ต.ต.ม.ล.', 'พลตำรวจตรีหม่อมหลวง');
INSERT INTO `tbl_prename` VALUES ('341', 'พล.ต.หญิง คุณหญิง', 'พลตรีหญิง คุณหญิง');
INSERT INTO `tbl_prename` VALUES ('342', 'ว่าที่ ส.อ.', 'ว่าที่สิบเอก');
INSERT INTO `tbl_prename` VALUES ('343', 'พล.ต.อ.ดร.', 'พลตำรวจเอกดอกเตอร์');
INSERT INTO `tbl_prename` VALUES ('344', 'สมเด็จพระสังฆราชเจ้า', 'สมเด็จพระสังฆราชเจ้า');
INSERT INTO `tbl_prename` VALUES ('345', 'สมเด็จพระสังฆราช', 'สมเด็จพระสังฆราช');
INSERT INTO `tbl_prename` VALUES ('346', 'สมเด็จพระราชาคณะ', 'สมเด็จพระราชาคณะ');
INSERT INTO `tbl_prename` VALUES ('347', 'รองสมเด็จพระราชาคณะ', 'รองสมเด็จพระราชาคณะ');
INSERT INTO `tbl_prename` VALUES ('348', 'พระราชาคณะ', 'พระราชาคณะ');
INSERT INTO `tbl_prename` VALUES ('349', 'พระเปรียญธรรม', 'พระเปรียญธรรม');
INSERT INTO `tbl_prename` VALUES ('350', 'พระหิรัญยบัฏ', 'พระหิรัญยบัฏ');
INSERT INTO `tbl_prename` VALUES ('351', 'พระสัญญาบัตร', 'พระสัญญาบัตร');
INSERT INTO `tbl_prename` VALUES ('352', 'พระราช', 'พระราช');
INSERT INTO `tbl_prename` VALUES ('353', 'พระเทพ', 'พระเทพ');
INSERT INTO `tbl_prename` VALUES ('354', 'พระปลัดขวา', 'พระปลัดขวา');
INSERT INTO `tbl_prename` VALUES ('355', 'พระปลัดซ้าย', 'พระปลัดซ้าย');
INSERT INTO `tbl_prename` VALUES ('356', 'พระครูปลัด', 'พระครูปลัด');
INSERT INTO `tbl_prename` VALUES ('357', 'พระครูปลัดสุวัฒนญาณคุณ', 'พระครูปลัดสุวัฒนญาณคุณ');
INSERT INTO `tbl_prename` VALUES ('358', 'พระครูปลัดอาจารย์วัฒน์', 'พระครูปลัดอาจารย์วัฒน์');
INSERT INTO `tbl_prename` VALUES ('359', 'พระครูปลัดวิมลสิริวัฒน์', 'พระครูวิมลสิริวัฒน์');
INSERT INTO `tbl_prename` VALUES ('360', 'พระสมุห์', 'พระสมุห์');
INSERT INTO `tbl_prename` VALUES ('361', 'พระครูสมุห์', 'พระครูสมุห์');
INSERT INTO `tbl_prename` VALUES ('362', 'พระครู', 'พระครู');
INSERT INTO `tbl_prename` VALUES ('363', 'พระครูใบฎีกา', 'พระครูใบฎีกา');
INSERT INTO `tbl_prename` VALUES ('364', 'พระครูธรรมธร', 'พระครูธรรมธร');
INSERT INTO `tbl_prename` VALUES ('365', 'พระครูวิมลภาณ', 'พระครูวิมลภาณ');
INSERT INTO `tbl_prename` VALUES ('366', 'พระครูศัพทมงคล', 'พระครูศัพทมงคล');
INSERT INTO `tbl_prename` VALUES ('367', 'พระครูสังฆภารวิชัย', 'พระครูสังฆภารวิชัย');
INSERT INTO `tbl_prename` VALUES ('368', 'พระครูสังฆรักษ์', 'พระครูสังฆรักษ์');
INSERT INTO `tbl_prename` VALUES ('369', 'พระครูสังฆวิชัย', 'พระครูสังฆวิชัย');
INSERT INTO `tbl_prename` VALUES ('370', 'พระครูสังฆวิชิต', 'พระครูสังฆวิชิต');
INSERT INTO `tbl_prename` VALUES ('371', 'พระปิฎก', 'พระปิฎก');
INSERT INTO `tbl_prename` VALUES ('372', 'พระปริยัติ', 'พระปริยัติ');
INSERT INTO `tbl_prename` VALUES ('373', 'เจ้าอธิการ', 'เจ้าอธิการ');
INSERT INTO `tbl_prename` VALUES ('374', 'พระอธิการ', 'พระอธิการ');
INSERT INTO `tbl_prename` VALUES ('375', 'พระ', 'พระ');
INSERT INTO `tbl_prename` VALUES ('376', 'ส.ณ.', 'สามเณร');
INSERT INTO `tbl_prename` VALUES ('377', 'พระปลัด', 'พระปลัด');
INSERT INTO `tbl_prename` VALUES ('378', 'สมเด็จพระอริยวงศาคตญาณ', 'สมเด็จพระอริยวงศาคตญาณ');
INSERT INTO `tbl_prename` VALUES ('379', 'พระคาร์ดินัล', 'พระคาร์ดินัล');
INSERT INTO `tbl_prename` VALUES ('380', 'พระสังฆราช', 'พระสังฆราช');
INSERT INTO `tbl_prename` VALUES ('381', 'พระคุณเจ้า', 'พระคุณเจ้า');
INSERT INTO `tbl_prename` VALUES ('382', 'บาทหลวง', 'บาทหลวง');
INSERT INTO `tbl_prename` VALUES ('383', 'พระมหา', 'พระมหา');
INSERT INTO `tbl_prename` VALUES ('384', 'พระราชปัญญา', 'พระราชปัญญา');
INSERT INTO `tbl_prename` VALUES ('385', 'ภาราดา', 'ภาราดา');
INSERT INTO `tbl_prename` VALUES ('386', 'พระศรีปริยัติธาดา', 'พระศรีปริยัติธาดา');
INSERT INTO `tbl_prename` VALUES ('387', 'พระญาณโศภณ', 'พระญาณโศภณ');
INSERT INTO `tbl_prename` VALUES ('388', 'สมเด็จพระมหาวีรวงศ์', 'สมเด็จพระมหาวีรวงศ์');
INSERT INTO `tbl_prename` VALUES ('389', 'พระโสภณธรรมาภรณ์', 'พระโสภณธรรมาภรณ์');
INSERT INTO `tbl_prename` VALUES ('390', 'พระวิริวัฒน์วิสุทธิ์', 'พระวิริวัฒน์วิสุทธิ์');
INSERT INTO `tbl_prename` VALUES ('391', 'พระญาณ', 'พระญาณ');
INSERT INTO `tbl_prename` VALUES ('392', 'พระอัครสังฆราช', 'พระอัครสังฆราช');
INSERT INTO `tbl_prename` VALUES ('393', 'พระธรรม', 'พระธรรม');
INSERT INTO `tbl_prename` VALUES ('394', 'พระสาสนโสภณ', 'พระสาสนโสภณ');
INSERT INTO `tbl_prename` VALUES ('395', 'พระธรรมโสภณ', 'พระธรรมโสภณ');
INSERT INTO `tbl_prename` VALUES ('396', 'พระอุดมสารโสภณ', 'พระอุดมสารโสภณ');
INSERT INTO `tbl_prename` VALUES ('397', 'พระครูวิมลญาณโสภณ', 'พระครูวิมลญาณโสภณ');
INSERT INTO `tbl_prename` VALUES ('398', 'พระครูปัญญาภรณโสภณ', 'พระครูปัญญาภรณโสภณ');
INSERT INTO `tbl_prename` VALUES ('399', 'พระครูโสภณปริยัติคุณ', 'พระครูโสภณปริยัติคุณ');
INSERT INTO `tbl_prename` VALUES ('400', 'พระอธิธรรม', 'พระอธิธรรม');
INSERT INTO `tbl_prename` VALUES ('401', 'พระราชญาณ', 'พระราชญาณ');
INSERT INTO `tbl_prename` VALUES ('402', 'พระสุธีวัชโรดม', 'พระสุธีวัชโรดม');
INSERT INTO `tbl_prename` VALUES ('403', 'รองเจ้าอธิการ', 'รองเจ้าอธิการ');
INSERT INTO `tbl_prename` VALUES ('404', 'พระครูวินัยธร', 'พระครูวินัยธร');
INSERT INTO `tbl_prename` VALUES ('405', 'พระศรีวชิราภรณ์', 'พระศรีวชิราภรณ์');
INSERT INTO `tbl_prename` VALUES ('406', 'พระราชบัณฑิต', 'พระราชบัณฑิต');
INSERT INTO `tbl_prename` VALUES ('407', 'แม่ชี', 'แม่ชี');
INSERT INTO `tbl_prename` VALUES ('408', 'นักบวช', 'นักบวช');
INSERT INTO `tbl_prename` VALUES ('409', 'พระรัตน', 'พระรัตน');
INSERT INTO `tbl_prename` VALUES ('410', 'พระโสภณปริยัติธรรม', 'พระโสภณปริยัติธรรม');
INSERT INTO `tbl_prename` VALUES ('411', 'พระครูวิศาลปัญญาคุณ', 'พระครูวิศาลปัญญาคุณ');
INSERT INTO `tbl_prename` VALUES ('412', 'พระศรีปริยัติโมลี', 'พระศรีปริยัติโมลี');
INSERT INTO `tbl_prename` VALUES ('413', 'พระครูวัชรสีลาภรณ์', 'พระครูวัชรสีลาภรณ์');
INSERT INTO `tbl_prename` VALUES ('414', 'พระครูพิพัฒน์บรรณกิจ', 'พระครูพิพัฒน์บรรณกิจ');
INSERT INTO `tbl_prename` VALUES ('415', 'พระครูวิบูลธรรมกิจ', 'พระครูวิบูลธรรมกิจ');
INSERT INTO `tbl_prename` VALUES ('416', 'พระครูพัฒนสารคุณ', 'พระครูพัฒนสารคุณ');
INSERT INTO `tbl_prename` VALUES ('417', 'พระครูสุวรรณพัฒนคุณ', 'พระครูสุวรรณพัฒนคุณ');
INSERT INTO `tbl_prename` VALUES ('418', 'พระครูพรหมวีรสุนทร', 'พระครูพรหมวีรสุนทร');
INSERT INTO `tbl_prename` VALUES ('419', 'พระครูอุปถัมภ์นันทกิจ', 'พระครูอุปถัมภ์นันทกิจ');
INSERT INTO `tbl_prename` VALUES ('420', 'พระครูวิจารณ์สังฆกิจ', 'พระครูวิจารณ์สังฆกิจ');
INSERT INTO `tbl_prename` VALUES ('421', 'พระครูวิมลสารวิสุทธิ์', 'พระครูวิมลสารวิสุทธิ์');
INSERT INTO `tbl_prename` VALUES ('422', 'พระครูไพศาลศุภกิจ', 'พระครูไพศาลศุภกิจ');
INSERT INTO `tbl_prename` VALUES ('423', 'พระครูโอภาสธรรมพิมล', 'พระครูโอภาสธรรมพิมล');
INSERT INTO `tbl_prename` VALUES ('424', 'พระครูพิพิธวรคุณ', 'พระครูพิพิธวรคุณ');
INSERT INTO `tbl_prename` VALUES ('425', 'พระครูสุนทรปภากร', 'พระครูสุนทรปภากร');
INSERT INTO `tbl_prename` VALUES ('426', 'พระครูสิริชัยสถิต', 'พระครูสิริชัยสถิต');
INSERT INTO `tbl_prename` VALUES ('427', 'พระครูเกษมธรรมานันท์', 'พระครูเกษมธรรมานันท์');
INSERT INTO `tbl_prename` VALUES ('428', 'พระครูถาวรสันติคุณ', 'พระครูถาวรสันติคุณ');
INSERT INTO `tbl_prename` VALUES ('429', 'พระครูวิสุทธาจารวิมล', 'พระครูวิสุทธาจารวิมล');
INSERT INTO `tbl_prename` VALUES ('430', 'พระครูปภัสสราธิคุณ', 'พระครูปภัสสราธิคุณ');
INSERT INTO `tbl_prename` VALUES ('431', 'พระครูวรสังฆกิจ', 'พระครูวรสังฆกิจ');
INSERT INTO `tbl_prename` VALUES ('432', 'พระครูไพบูลชัยสิทธิ์', 'พระครูไพบูลชัยสิทธิ์');
INSERT INTO `tbl_prename` VALUES ('433', 'พระครูโกวิทธรรมโสภณ', 'พระครูโกวิทธรรมโสภณ');
INSERT INTO `tbl_prename` VALUES ('434', 'พระครูสุพจน์วราภรณ์', 'พระครูสุพจน์วราภรณ์');
INSERT INTO `tbl_prename` VALUES ('435', 'พระครูไพโรจน์อริญชัย', 'พระครูไพโรจน์อริญชัย');
INSERT INTO `tbl_prename` VALUES ('436', 'พระครูสุนทรคณาภิรักษ์', 'พระครูสุนทรคณาภิรักษ์');
INSERT INTO `tbl_prename` VALUES ('437', 'พระสรภาณโกศล', 'พระสรภาณโกศล');
INSERT INTO `tbl_prename` VALUES ('438', 'พระครูประโชติธรรมรัตน์', 'พระครูประโชติธรรมรัตน์');
INSERT INTO `tbl_prename` VALUES ('439', 'พระครูจารุธรรมกิตติ์', 'พระครูจารุธรรมกิตติ์');
INSERT INTO `tbl_prename` VALUES ('440', 'พระครูพิทักษ์พรหมรังษี', 'พระครูพิทักษ์พรหมรังษี');
INSERT INTO `tbl_prename` VALUES ('441', 'พระศรีปริยัติบัณฑิต', 'พระศรีปริยัติบัณฑิต');
INSERT INTO `tbl_prename` VALUES ('442', 'พระครูพุทธิธรรมานุศาสน์', 'พระครูพุทธิธรรมานุศาสน์');
INSERT INTO `tbl_prename` VALUES ('443', 'พระธรรมเมธาจารย์', 'พระธรรมเมธาจารย์');
INSERT INTO `tbl_prename` VALUES ('444', 'พระครูกิตติกาญจนวงศ์', 'พระครูกิตติกาญจนวงศ์');
INSERT INTO `tbl_prename` VALUES ('445', 'พระครูปลัดสัมพิพัฒนวิริยาจารย์', 'พระครูปลัดสัมพิพัฒนวิริยาจารย์');
INSERT INTO `tbl_prename` VALUES ('446', 'พระครูศีลกันตาภรณ์', 'พระครูศีลกันตาภรณ์');
INSERT INTO `tbl_prename` VALUES ('447', 'พระครูประกาศพุทธพากย์', 'พระครูประกาศพุทธพากย์');
INSERT INTO `tbl_prename` VALUES ('448', 'พระครูอมรวิสุทธิคุณ', 'พระครูอมรวิสุทธิคุณ');
INSERT INTO `tbl_prename` VALUES ('449', 'พระครูสุทัศน์ธรรมาภิรม', 'พระครูสุทัศน์ธรรมาภิรม');
INSERT INTO `tbl_prename` VALUES ('450', 'พระครูอุปถัมภ์วชิโรภาส', 'พระครูอุปถัมภ์วชิโรภาส');
INSERT INTO `tbl_prename` VALUES ('451', 'พระครูสุนทรสมณคุณ', 'พระครูสุนทรสมณคุณ');
INSERT INTO `tbl_prename` VALUES ('452', 'พระพรหมมุนี', 'พระพรหมมุนี');
INSERT INTO `tbl_prename` VALUES ('453', 'พระครูสิริคุณารักษ์', 'พระครูสิริคุณารักษ์');
INSERT INTO `tbl_prename` VALUES ('454', 'พระครูวิชิตพัฒนคุณ', 'พระครูวิชิตพัฒนคุณ');
INSERT INTO `tbl_prename` VALUES ('455', 'พระครูพิบูลโชติธรรม', 'พระครูพิบูลโชติธรรม');
INSERT INTO `tbl_prename` VALUES ('456', 'พระพิศาลสารคุณ', 'พระพิศาลสารคุณ');
INSERT INTO `tbl_prename` VALUES ('457', 'พระรัตนมงคลวิสุทธ์', 'พระรัตนมงคลวิสุทธ์');
INSERT INTO `tbl_prename` VALUES ('458', 'พระครูโสภณคุณานุกูล', 'พระครูโสภณคุณานุกูล');
INSERT INTO `tbl_prename` VALUES ('459', 'พระครูผาสุกวิหารการ', 'พระครูผาสุกวิหารการ');
INSERT INTO `tbl_prename` VALUES ('460', 'พระครูวชิรวุฒิกร', 'พระครูวชิรวุฒิกร');
INSERT INTO `tbl_prename` VALUES ('461', 'พระครูกาญจนยติกิจ', 'พระครูกาญจนยติกิจ');
INSERT INTO `tbl_prename` VALUES ('462', 'พระครูบวรรัตนวงศ์', 'พระครูบวรรัตนวงศ์');
INSERT INTO `tbl_prename` VALUES ('463', 'พระราชพัชราภรณ์', 'พระราชพัชราภรณ์');
INSERT INTO `tbl_prename` VALUES ('464', 'พระครูพิพิธอุดมคุณ', 'พระครูพิพิธอุดมคุณ');
INSERT INTO `tbl_prename` VALUES ('465', 'องสุตบทบวร', 'องสุตบทบวร');
INSERT INTO `tbl_prename` VALUES ('466', 'พระครูจันทเขมคุณ', 'พระครูจันทเขมคุณ');
INSERT INTO `tbl_prename` VALUES ('467', 'พระครูศีลสารวิสุทธิ์', 'พระครูศีลสารวิสุทธิ์');
INSERT INTO `tbl_prename` VALUES ('468', 'พระครูสุธรรมโสภิต', 'พระครูสุธรรมโสภิต');
INSERT INTO `tbl_prename` VALUES ('469', 'พระครูอุเทศธรรมนิวิฐ', 'พระครูอุเทศธรรมนิวิฐ');
INSERT INTO `tbl_prename` VALUES ('470', 'พระครูบรรณวัตร', 'พระครูบรรณวัตร');
INSERT INTO `tbl_prename` VALUES ('471', 'พระครูวิสุทธาจาร', 'พระครูวิสุทธาจาร');
INSERT INTO `tbl_prename` VALUES ('472', 'พระครูสุนทรวรวัฒน์', 'พระครูสุนทรวรวัฒน์');
INSERT INTO `tbl_prename` VALUES ('473', 'พระเทพชลธารมุนี ศรีชลบุราจารย์', 'พระเทพชลธารมุนี ศรีชลบุราจารย์');
INSERT INTO `tbl_prename` VALUES ('474', 'พระครูโสภณสมุทรคุณ', 'พระครูโสภณสมุทรคุณ');
INSERT INTO `tbl_prename` VALUES ('475', 'พระราชเมธาภรณ์', 'พระราชเมธาภรณ์');
INSERT INTO `tbl_prename` VALUES ('476', 'พระครูศรัทธาธรรมโสภณ', 'พระครูศรัทธาธรรมโสภณ');
INSERT INTO `tbl_prename` VALUES ('477', 'พระครูสังฆบริรักษ์', 'พระครูสังฆบริรักษ์');
INSERT INTO `tbl_prename` VALUES ('478', 'พระมหานายก', 'พระมหานายก');
INSERT INTO `tbl_prename` VALUES ('479', 'พระครูโอภาสสมาจาร', 'พระครูโอภาสสมาจาร');
INSERT INTO `tbl_prename` VALUES ('480', 'พระครูศรีธวัชคุณาภรณ์', 'พระครูศรีธวัชคุณาภรณ์');
INSERT INTO `tbl_prename` VALUES ('481', 'พระครูโสภิตวัชรกิจ', 'พระครูโสภิตวัชรกิจ');
INSERT INTO `tbl_prename` VALUES ('482', 'พระราชวชิราภรณ์', 'พระราชวชิราภรณ์');
INSERT INTO `tbl_prename` VALUES ('483', 'พระครูสุนทรวรธัช', 'พระครูสุนทรวรธัช');
INSERT INTO `tbl_prename` VALUES ('484', 'พระครูอาทรโพธิกิจ', 'พระครูอาทรโพธิกิจ');
INSERT INTO `tbl_prename` VALUES ('485', 'พระครูวิบูลกาญจนกิจ', 'พระครูวิบูลกาญจนกิจ');
INSERT INTO `tbl_prename` VALUES ('486', 'พระพรหมวชิรญาณ', 'พระพรหมวชิรญาณ');
INSERT INTO `tbl_prename` VALUES ('487', 'พระครูสุพจน์วรคุณ', 'พระครูสุพจน์วรคุณ');
INSERT INTO `tbl_prename` VALUES ('488', 'พระราชวิมลโมลี', 'พระราชาวิมลโมลี');
INSERT INTO `tbl_prename` VALUES ('489', 'พระครูอมรธรรมนายก', 'พระครูอมรธรรมนายก');
INSERT INTO `tbl_prename` VALUES ('490', 'พระครูพิศิษฎ์ศาสนการ', 'พระครูพิศิษฎ์ศาสนการ');
INSERT INTO `tbl_prename` VALUES ('491', 'พระครูเมธีธรรมานุยุต', 'พระครูเมธีธรรมานุยุต');
INSERT INTO `tbl_prename` VALUES ('492', 'พระครูปิยสีลสาร', 'พระครูปิยสีลสาร');
INSERT INTO `tbl_prename` VALUES ('493', 'พระครูสถิตบุญวัฒน์', 'พระครูสถิตบุญวัฒน์');
INSERT INTO `tbl_prename` VALUES ('494', 'พระครูนิเทศปิยธรรม', 'พระครูนิเทศปิยธรรม');
INSERT INTO `tbl_prename` VALUES ('495', 'พระครูวิสุทธิ์กิจจานุกูล', 'พระครูวิสุทธิ์กิจจานุกูล');
INSERT INTO `tbl_prename` VALUES ('496', 'พระครูสถิตย์บุญวัฒน์', 'พระครูสถิตย์บุญวัฒน์');
INSERT INTO `tbl_prename` VALUES ('497', 'พระครูประโชติธรรมานุกูล', 'พระครูประโชติธรรมานุกูล');
INSERT INTO `tbl_prename` VALUES ('498', 'พระเทพญาณกวี', 'พระเทพญาณกวี');
INSERT INTO `tbl_prename` VALUES ('499', 'พระครูพิพัฒน์ชินวงศ์', 'พระครูพิพัฒน์ชินวงศ์');
INSERT INTO `tbl_prename` VALUES ('500', 'พระครูสมุทรขันตยาภรณ์', 'พระครูสมุทรขันตยาภรณ์');
INSERT INTO `tbl_prename` VALUES ('501', 'พระครูภาวนาวรกิจ', 'พระครูภาวนาวรกิจ');
INSERT INTO `tbl_prename` VALUES ('502', 'พระครูศรีศาสนคุณ', 'พระครูศรีศาสนคุณ');
INSERT INTO `tbl_prename` VALUES ('503', 'พระครูวิบูลย์ธรรมศาสก์', 'พระครูวิบูลย์ธรรมศาสก์');
