/*
Navicat MySQL Data Transfer

Source Server         : localhost
Source Server Version : 50617
Source Host           : localhost:3306
Source Database       : detoxthai_lte

Target Server Type    : MYSQL
Target Server Version : 50617
File Encoding         : 65001

Date: 2015-06-05 19:15:34
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for tbl_job
-- ----------------------------
DROP TABLE IF EXISTS `tbl_job`;
CREATE TABLE `tbl_job` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `job_name` varchar(255) COLLATE utf8_unicode_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=777 DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

-- ----------------------------
-- Records of tbl_job
-- ----------------------------
INSERT INTO `tbl_job` VALUES ('1', 'ทหารชั้นสัญญาบัตร');
INSERT INTO `tbl_job` VALUES ('2', 'ทหารชั้นประทวน');
INSERT INTO `tbl_job` VALUES ('3', 'ทหารยศอื่นๆ');
INSERT INTO `tbl_job` VALUES ('4', 'ข้าราชการการเมืองและนักการเมือง');
INSERT INTO `tbl_job` VALUES ('5', 'ข้าราชการระดับอาวุโส');
INSERT INTO `tbl_job` VALUES ('6', 'ผู้บัญชาการตำรวจแห่งชาติ');
INSERT INTO `tbl_job` VALUES ('7', 'จเรตำรวจ');
INSERT INTO `tbl_job` VALUES ('8', 'กำนัน');
INSERT INTO `tbl_job` VALUES ('9', 'ผู้ใหญ่บ้าน');
INSERT INTO `tbl_job` VALUES ('10', 'หัวหน้าหมู่บ้าน');
INSERT INTO `tbl_job` VALUES ('11', 'กรรมการผู้จัดการและผู้บริหารระดับสูงภาคเอกชน');
INSERT INTO `tbl_job` VALUES ('12', 'ผู้จัดการด้านบริการและบริหารจัดการวิสาหกิจ');
INSERT INTO `tbl_job` VALUES ('13', 'ผู้จัดการด้านการเงินภาครัฐ/รัฐวิสาหกิจ/เอกชน');
INSERT INTO `tbl_job` VALUES ('14', 'ผู้จัดการด้านทรัพยากรบุคคลภาครัฐ/รัฐวิสาหกิจ/เอกชน');
INSERT INTO `tbl_job` VALUES ('15', 'ผู้จัดการด้านนโยบายและแผนภาครัฐ/รัฐวิสาหกิจ/เอกชน');
INSERT INTO `tbl_job` VALUES ('16', 'ผู้จัดการด้านบริการและบริหารจัดการภาครัฐ/รัฐวิสาหกิจ/เอกชน ซึ่งมิได้จัดประเภทไว้ที่อื่น');
INSERT INTO `tbl_job` VALUES ('17', 'ผู้จัดการด้านการขาย การตลาด และการพัฒนาธุรกิจภาครัฐ/รัฐวิสาหกิจ/เอกชน');
INSERT INTO `tbl_job` VALUES ('18', 'ผู้จัดการด้านการขาย ภาครัฐ/รัฐวิสาหกิจ/เอกชน');
INSERT INTO `tbl_job` VALUES ('19', 'ผู้จัดการด้านการตลาด ภาครัฐ/รัฐวิสาหกิจ/เอกชน');
INSERT INTO `tbl_job` VALUES ('20', 'ผู้จัดการด้านโฆษณาและประชาสัมพันธ์ ภาครัฐ/รัฐวิสาหกิจ/เอกชน');
INSERT INTO `tbl_job` VALUES ('21', 'ผู้จัดการด้านวิจัยและพัฒนา ภาครัฐ/รัฐวิสาหกิจ/เอกชน');
INSERT INTO `tbl_job` VALUES ('22', 'ผู้จัดการด้านการผลิตในภาคการเกษตรและการป่าไม้');
INSERT INTO `tbl_job` VALUES ('23', 'ผู้จัดการผลิตด้านป่าไม้');
INSERT INTO `tbl_job` VALUES ('24', 'ผู้จัดการผลิตด้านเพาะปลูก');
INSERT INTO `tbl_job` VALUES ('25', 'ผู้จัดการผลิตด้านการเลี้ยงปศุสัตว์');
INSERT INTO `tbl_job` VALUES ('26', 'ผู้จัดการฟาร์มปศุสัตว์');
INSERT INTO `tbl_job` VALUES ('27', 'ผู้จัดการด้านการผลิตในภาคการเพาะเลี้ยงสัตว์น้ำและการประมง');
INSERT INTO `tbl_job` VALUES ('28', 'ผู้จัดการฝ่ายผลิตด้านการเพาะเลี้ยงสัตว์น้ำ');
INSERT INTO `tbl_job` VALUES ('29', 'ผู้จัดการฝ่ายผลิตด้านการประมง');
INSERT INTO `tbl_job` VALUES ('30', 'ผู้จัดการเรือลากอวน');
INSERT INTO `tbl_job` VALUES ('31', 'ผู้จัดการด้านการผลิตภาครัฐวิสาหกิจและเอกชน');
INSERT INTO `tbl_job` VALUES ('32', 'ผู้จัดการด้านการทำ/ผลิตเหมืองแร่');
INSERT INTO `tbl_job` VALUES ('33', 'ผู้จัดการด้านการทำ/ผลิตเหมืองหิน');
INSERT INTO `tbl_job` VALUES ('34', 'ผู้จัดการฝ่ายผลิตในการขุดเจาะน้ำมันและก๊าซ');
INSERT INTO `tbl_job` VALUES ('35', 'ผู้จัดการโครงการก่อสร้าง');
INSERT INTO `tbl_job` VALUES ('36', 'ผู้รับเหมาก่อสร้าง');
INSERT INTO `tbl_job` VALUES ('37', 'ผู้จัดการด้านการจัดหาและจัดส่งสินค้า');
INSERT INTO `tbl_job` VALUES ('38', 'ผู้จัดการสถานีรถประจำทาง');
INSERT INTO `tbl_job` VALUES ('39', 'ผู้จัดการสถานีรถไฟ');
INSERT INTO `tbl_job` VALUES ('40', 'ผู้จัดการบริษัทขนส่ง');
INSERT INTO `tbl_job` VALUES ('41', 'ผู้จัดการด้านการบริการเทคโนโลยีสารสนเทศและการสื่อสารภาครัฐวิสาหกิจและเอกชน');
INSERT INTO `tbl_job` VALUES ('42', 'ผู้จัดการด้านการบริการดูแลเด็ก');
INSERT INTO `tbl_job` VALUES ('43', 'ผู้จัดการด้านการบริการสุขภาพ');
INSERT INTO `tbl_job` VALUES ('44', 'ผู้อำนวยการคลินิก');
INSERT INTO `tbl_job` VALUES ('45', 'ผู้อำนวยการสถานพยาบาล');
INSERT INTO `tbl_job` VALUES ('46', 'ผู้จัดการด้านการบริการดูแลผู้สูงอายุ');
INSERT INTO `tbl_job` VALUES ('47', 'ผู้จัดการบ้านพักคนชรา');
INSERT INTO `tbl_job` VALUES ('48', 'ผู้จัดการด้านงานสังคมสงเคราะห์');
INSERT INTO `tbl_job` VALUES ('49', 'ผู้จัดการด้านการศึกษา');
INSERT INTO `tbl_job` VALUES ('50', 'ผู้อำนวยการวิทยาลัย');
INSERT INTO `tbl_job` VALUES ('51', 'ครูใหญ่');
INSERT INTO `tbl_job` VALUES ('52', 'คณบดีมหาวิทยาลัย');
INSERT INTO `tbl_job` VALUES ('53', 'ผู้อำนวยการโรงเรียน');
INSERT INTO `tbl_job` VALUES ('54', 'ผู้จัดการธนาคาร');
INSERT INTO `tbl_job` VALUES ('55', 'ผู้จัดการสาขาสถานบันการเงิน');
INSERT INTO `tbl_job` VALUES ('56', 'ผู้จัดการสหกรณ์เคหะ');
INSERT INTO `tbl_job` VALUES ('57', 'ผู้จัดการด้านการประกนภัย');
INSERT INTO `tbl_job` VALUES ('58', 'ผู้กำกับการตำรวจ');
INSERT INTO `tbl_job` VALUES ('59', 'ผู้บัญชาการเรือนจำ');
INSERT INTO `tbl_job` VALUES ('60', 'ผู้จัดการโรงแรม');
INSERT INTO `tbl_job` VALUES ('61', 'ผู้จัดการภัตตาคาร/ร้านอาหาร');
INSERT INTO `tbl_job` VALUES ('62', 'ผู้จัดการด้านการค้าส่ง และค้าปลีก');
INSERT INTO `tbl_job` VALUES ('63', 'ผู้จัดการด้านการกีฬา นันทนาการ และศูนย์วัฒนธรรม');
INSERT INTO `tbl_job` VALUES ('64', 'ผู้จัดการด้านการบริการ ซึ่งมิได้จัดประเภทไว้ในที่อื่น');
INSERT INTO `tbl_job` VALUES ('65', 'นักฟิสิกส์และนักดาราศาสตร์');
INSERT INTO `tbl_job` VALUES ('66', 'นักฟิสิกส์การแพทย์');
INSERT INTO `tbl_job` VALUES ('67', 'นักนิวเคลียร์ฟิสิกส์');
INSERT INTO `tbl_job` VALUES ('68', 'นักอุตุนิยมวิทยา');
INSERT INTO `tbl_job` VALUES ('69', 'นักเคมี');
INSERT INTO `tbl_job` VALUES ('70', 'นักธรณีวิทยาและนักธรณีฟิสิกส์');
INSERT INTO `tbl_job` VALUES ('71', 'นักคณิตศาสตร์ นักคณิตศาสตร์ประกนภัยและนักสถิติ');
INSERT INTO `tbl_job` VALUES ('72', 'นักชีววิทยา นักพฤกษศาสตร์ นักสัตวศาสตร์ และผู้ประกอบวิชาชีพที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('73', 'ผู้ให้คำปรึกษาด้านการเกษตร การป่าไม้ และการประมง');
INSERT INTO `tbl_job` VALUES ('74', 'นักวิชาการพืชสวน');
INSERT INTO `tbl_job` VALUES ('75', 'ผู้ประกอบวิชีพด้านการรักษาสิ่งแวดล้อม');
INSERT INTO `tbl_job` VALUES ('76', 'วิศวกรอุตสาหการและการผลิต');
INSERT INTO `tbl_job` VALUES ('77', 'วิศวกรโยธา');
INSERT INTO `tbl_job` VALUES ('78', 'วิศวกรสิ่งแวดล้อม');
INSERT INTO `tbl_job` VALUES ('79', 'วิศวกรเครื่องกล');
INSERT INTO `tbl_job` VALUES ('80', 'วิศวกรอากาศยาน');
INSERT INTO `tbl_job` VALUES ('81', 'วิศวกรต่อเรือ');
INSERT INTO `tbl_job` VALUES ('82', 'วิศวกรเคมี');
INSERT INTO `tbl_job` VALUES ('83', 'วิศวกรเหมืองแร่ นักโลหะกรรม และผู้ประกอบวิชาชีพที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('84', 'วิศวกร (ยกเว้นวิศวกรเทคโนโลยีไฟฟ้า) ซึ่งมิได้จัดประเภทไว้ที่อื่น');
INSERT INTO `tbl_job` VALUES ('85', 'วิศวกรไฟฟ้า');
INSERT INTO `tbl_job` VALUES ('86', 'วิศวกรอิเล็กทรอนิกส์');
INSERT INTO `tbl_job` VALUES ('87', 'วิศวกรคอมพิวเตอร์ฮาร์ดแวร์');
INSERT INTO `tbl_job` VALUES ('88', 'วิศวกรโทรคมนาคม');
INSERT INTO `tbl_job` VALUES ('89', 'สถาปนิกก่อสร้าง และออกแบบภายใน');
INSERT INTO `tbl_job` VALUES ('90', 'นักทำแผนที่และนักสำรวจ');
INSERT INTO `tbl_job` VALUES ('91', 'นักภูมิสถาปัตย์');
INSERT INTO `tbl_job` VALUES ('92', 'นักออกแบบผลิตภัณฑ์และเครื่องแต่งกาย');
INSERT INTO `tbl_job` VALUES ('93', 'นักวางผังเมือง และระบบการจราจร');
INSERT INTO `tbl_job` VALUES ('94', 'นักออกแบบภาพกราฟฟิกและสื่อผสม');
INSERT INTO `tbl_job` VALUES ('95', 'แพทย์ทั่วไป');
INSERT INTO `tbl_job` VALUES ('96', 'แพทย์เฉพาะทาง');
INSERT INTO `tbl_job` VALUES ('97', 'พยาบาล');
INSERT INTO `tbl_job` VALUES ('98', 'ผดุงครรภ์วิชาชีพ');
INSERT INTO `tbl_job` VALUES ('99', 'แพทย์แผนโบราณและแพทย์ทางเลือก');
INSERT INTO `tbl_job` VALUES ('100', 'ผู้ช่วยแพทย์');
INSERT INTO `tbl_job` VALUES ('101', 'สัตวแพทย์');
INSERT INTO `tbl_job` VALUES ('102', 'ทันตแพทย์');
INSERT INTO `tbl_job` VALUES ('103', 'เภสัชกร');
INSERT INTO `tbl_job` VALUES ('104', 'ผู้ประกอบวิชาชีพด้านสุขภาพและสุขอนามัยที่เกี่ยวข้องกับสิ่งแวดล้อมและการประกอบวิชาชีพ');
INSERT INTO `tbl_job` VALUES ('105', 'ผู้เชี่ยวชาญด้านการป้องกันรังสี');
INSERT INTO `tbl_job` VALUES ('106', 'นักกายภาพบำบัด');
INSERT INTO `tbl_job` VALUES ('107', 'นักโภชนาการ');
INSERT INTO `tbl_job` VALUES ('108', 'นักแก้ไขการได้ยินและการพูด');
INSERT INTO `tbl_job` VALUES ('109', 'นักศิลปะบำบัด');
INSERT INTO `tbl_job` VALUES ('110', 'นักเคลื่อนไหวบำบัด');
INSERT INTO `tbl_job` VALUES ('111', 'นักกิจกรรมบำบัด/อาชีวบำบัด');
INSERT INTO `tbl_job` VALUES ('112', 'นักนันทนาการบำบัด');
INSERT INTO `tbl_job` VALUES ('113', 'ครูสอนระดับมหาวิทยาลัยและระดับอุดมศึกษา');
INSERT INTO `tbl_job` VALUES ('114', 'ครูสอนระดับอาชีวศึกษา');
INSERT INTO `tbl_job` VALUES ('115', 'ครูสอนระดับมัธยมศึกษา');
INSERT INTO `tbl_job` VALUES ('116', 'ครูสอนระดับประถมศึกษา');
INSERT INTO `tbl_job` VALUES ('117', 'ครูสอนระดับปฐมวัย');
INSERT INTO `tbl_job` VALUES ('118', 'ผู้เชี่ยวชาญด้านการศึกษา');
INSERT INTO `tbl_job` VALUES ('119', 'ครูสอนพิเศษ');
INSERT INTO `tbl_job` VALUES ('120', 'ครูสอนภาษา');
INSERT INTO `tbl_job` VALUES ('121', 'ครูสอนดนตรี');
INSERT INTO `tbl_job` VALUES ('122', 'ครูสอนศิลปะ');
INSERT INTO `tbl_job` VALUES ('123', 'ผู้ฝึกอบรมด้านเทคโนโลยีสารสนเทศ');
INSERT INTO `tbl_job` VALUES ('124', 'นักบัญชี');
INSERT INTO `tbl_job` VALUES ('125', 'ที่ปรึกษาด้านการเงิน');
INSERT INTO `tbl_job` VALUES ('126', 'นักวิเคราะห์การเงิน');
INSERT INTO `tbl_job` VALUES ('127', 'นักวิเคราะห์ด้านการบริหารและองค์การ');
INSERT INTO `tbl_job` VALUES ('128', 'นักวิเคราะห์นโยบาย');
INSERT INTO `tbl_job` VALUES ('129', 'เจ้าหน้าที่ข่าวกรอง');
INSERT INTO `tbl_job` VALUES ('130', 'ที่ปรึกษาด้านการเมือง');
INSERT INTO `tbl_job` VALUES ('131', 'ผู้ประกอบวิชาชีพด้านงานบุคคลและอาชีพ');
INSERT INTO `tbl_job` VALUES ('132', 'ผู้ประกอบวิชาชีพด้านการฝึกอบรมและการพัฒนาพนักงาน');
INSERT INTO `tbl_job` VALUES ('133', 'ผู้ประกอบวิชาชีพด้านโฆษณาและการตลาด');
INSERT INTO `tbl_job` VALUES ('134', 'ผู้ประกอบวิชาชีพด้านการประชาสัมพันธ์');
INSERT INTO `tbl_job` VALUES ('135', 'ผู้ประกอบวิชาชีพการขายด้านเทคนิคและด้านการแพทย์ (ยกเว้นด้านเทคโนโลยีสารสนเทศและการสื่อสาร)');
INSERT INTO `tbl_job` VALUES ('136', 'ผู้ประกอบวิชาชีพการขายด้านเทคโนโลยีสารสนเทศและการสื่อสาร');
INSERT INTO `tbl_job` VALUES ('137', 'นักวิเคราะห์ระบบคอมพิวเตอร์');
INSERT INTO `tbl_job` VALUES ('138', 'นักวิทยาศาสตร์คอมพิวเตอร์');
INSERT INTO `tbl_job` VALUES ('139', 'นักวิเคราะห์ธุรกิจด้านเทคโนโลยีสานสนเทศและการสื่อสาร');
INSERT INTO `tbl_job` VALUES ('140', 'นักพัฒนาซอฟต์แวร์');
INSERT INTO `tbl_job` VALUES ('141', 'นักพัฒนาเว็บไซต์และสื่อผสม');
INSERT INTO `tbl_job` VALUES ('142', 'โปรแกรมเมอร์');
INSERT INTO `tbl_job` VALUES ('143', 'นักวิเคราะห์และพัฒนาซอฟแวร์และโปรแกรมประยุกต์');
INSERT INTO `tbl_job` VALUES ('144', 'นักออกแบบและผู้บริหารฐานข้อมูล');
INSERT INTO `tbl_job` VALUES ('145', 'ผู้บริหารระบบงานคอมพิวเตอร์');
INSERT INTO `tbl_job` VALUES ('146', 'ผู้ประกอบวิชาชีพด้านเครือข่ายคอมพิวเตอร์');
INSERT INTO `tbl_job` VALUES ('147', 'นักวิเคราะห์ระบบสื่อสาร');
INSERT INTO `tbl_job` VALUES ('148', 'นักวิเคราะห์ระบบเครือข่าย');
INSERT INTO `tbl_job` VALUES ('149', 'ผู้เชี่ยวชาญด้านความปลอดภัยในระบบเทคโนโลยีสารสนเทศและการสื่อสาร');
INSERT INTO `tbl_job` VALUES ('150', 'อัยการ');
INSERT INTO `tbl_job` VALUES ('151', 'นิติกร');
INSERT INTO `tbl_job` VALUES ('152', 'นักกฎหมาย/เนติบัณทิต');
INSERT INTO `tbl_job` VALUES ('153', 'ทนายความ');
INSERT INTO `tbl_job` VALUES ('154', 'ผู้พิพากษา');
INSERT INTO `tbl_job` VALUES ('155', 'ผู้ประกอบวิชาชีพ ด้านกฎหมายซึ่งมิได้จัดประเภทๆไว้ที่อื่น');
INSERT INTO `tbl_job` VALUES ('156', 'จ่าศาล');
INSERT INTO `tbl_job` VALUES ('157', 'เจ้าหน้าที่ชันสูตรศพ');
INSERT INTO `tbl_job` VALUES ('158', 'ผู้เก็บหรือดูแลเอกสารหรือบันทึกสำคัญและภัณฑารักษ์');
INSERT INTO `tbl_job` VALUES ('159', 'บรรณารักษ์และผู้ประกอบวิชาชีพด้านงานสารสนเทศที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('160', 'นักเศรษฐศาสตร์');
INSERT INTO `tbl_job` VALUES ('161', 'นักสังคมวิทยา นักมานุษยวิทยา และผู้ประกอบวิชาชีพที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('162', 'นักปรัชญา นักประวัติศาสตร์ และนักรัฐศาสตร์');
INSERT INTO `tbl_job` VALUES ('163', 'นักจิตวิทยา');
INSERT INTO `tbl_job` VALUES ('164', 'นักสังคมสงเคราะห์');
INSERT INTO `tbl_job` VALUES ('165', 'ผู้ประกอบวิชาชีพด้านศาสนา');
INSERT INTO `tbl_job` VALUES ('166', 'นักประพันธ์และนักเขียน');
INSERT INTO `tbl_job` VALUES ('167', 'นักหนังสือพิมพ์');
INSERT INTO `tbl_job` VALUES ('168', 'ผู้สื่อข่าว/โทรทัศน์/วิทยุ');
INSERT INTO `tbl_job` VALUES ('169', 'ผู้สื่อข่าวหนังสือพิมพ์');
INSERT INTO `tbl_job` VALUES ('170', 'นักแปล ล่ามและนักภาษาศาสตร์อื่นๆ');
INSERT INTO `tbl_job` VALUES ('171', 'ประติมากร');
INSERT INTO `tbl_job` VALUES ('172', 'นักวาดภาพ');
INSERT INTO `tbl_job` VALUES ('173', 'ช่างศิลป์');
INSERT INTO `tbl_job` VALUES ('174', 'นักทัศนศิลป์');
INSERT INTO `tbl_job` VALUES ('175', 'นักปั้นเซรามิก');
INSERT INTO `tbl_job` VALUES ('176', 'นักร้อง');
INSERT INTO `tbl_job` VALUES ('177', 'นักดนตรี');
INSERT INTO `tbl_job` VALUES ('178', 'นักประพันธ์เพลง');
INSERT INTO `tbl_job` VALUES ('179', 'วาทยากร');
INSERT INTO `tbl_job` VALUES ('180', 'นักเต้นรำและนักออกแบบท่าเต้น');
INSERT INTO `tbl_job` VALUES ('181', 'นักบัลเลย์');
INSERT INTO `tbl_job` VALUES ('182', 'ผู้กำกับและผู้ผลิตภาพยนตร์ ละครและงานสาขาอื่นๆ ที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('183', 'เจ้าหน้าที่ตัดต่อภาพยนตร์');
INSERT INTO `tbl_job` VALUES ('184', 'นักแสดง');
INSERT INTO `tbl_job` VALUES ('185', 'ผู้ประกาศทางวิทยุ โทรทัศน์ และผู้ประกาศด้านอื่นๆ');
INSERT INTO `tbl_job` VALUES ('186', 'นักจัดรายการทอล์คโชว์');
INSERT INTO `tbl_job` VALUES ('187', 'นักกายกรรม');
INSERT INTO `tbl_job` VALUES ('188', 'นักแสดงตลก');
INSERT INTO `tbl_job` VALUES ('189', 'นักมายากล');
INSERT INTO `tbl_job` VALUES ('190', 'นักพากย์');
INSERT INTO `tbl_job` VALUES ('191', 'นักเชิดหุ่นกระบอก');
INSERT INTO `tbl_job` VALUES ('192', 'ช่างเทคนิคด้านเคมีและวิทยาศาสตร์กายภาพ');
INSERT INTO `tbl_job` VALUES ('193', 'ช่างเทคนิคด้านธรณีวิทยา');
INSERT INTO `tbl_job` VALUES ('194', 'ช่างเทคนิคด้านอุตุนิยมวิทยา');
INSERT INTO `tbl_job` VALUES ('195', 'ช่างเทคนิคด้านวิศวกรรมโยธา');
INSERT INTO `tbl_job` VALUES ('196', 'เจ้าหน้าที่ตรวจสอบอาคาร');
INSERT INTO `tbl_job` VALUES ('197', 'ผู้ควบคุมดูแลวัสดุก่อสร้างและคนงาน');
INSERT INTO `tbl_job` VALUES ('198', 'ช่างเทคนิคด้านการสำรวจ');
INSERT INTO `tbl_job` VALUES ('199', 'เจ้าหน้าที่ตรวจสอบสถานที่เกิดเพลิงไหม้');
INSERT INTO `tbl_job` VALUES ('200', 'เจ้าหน้าที่ตรวจสอบสถานที่เกิดเพลิงไหม้');
INSERT INTO `tbl_job` VALUES ('201', 'ผู้เชี่ยวชาญด้านการป้องกันไฟไหม้');
INSERT INTO `tbl_job` VALUES ('202', 'ช่างเทคนิคด้านวิศวกรรมไฟฟ้า');
INSERT INTO `tbl_job` VALUES ('203', 'ช่างเทคนิคด้านวิศวกรรมอิเล็กทรอนิกส์');
INSERT INTO `tbl_job` VALUES ('204', 'ช่างเทคนิคด้านวิศวกรรมเครื่องกล');
INSERT INTO `tbl_job` VALUES ('205', 'เจ้าหน้าที่สำรวจทางทะเล');
INSERT INTO `tbl_job` VALUES ('206', 'ช่างเทคนิคด้านวิศวกรรมเคมี');
INSERT INTO `tbl_job` VALUES ('207', 'ช่างเทคนิคด้านเหมืองแร่และโลหะวิทยา');
INSERT INTO `tbl_job` VALUES ('208', 'ช่างสำรวจเหมืองแร่');
INSERT INTO `tbl_job` VALUES ('209', 'ช่างเขียนแบบ');
INSERT INTO `tbl_job` VALUES ('210', 'เจ้าหน้าที่เทคนิคด้านนิติวิทยาศาสตร์');
INSERT INTO `tbl_job` VALUES ('211', 'เจ้าหน้าที่ตรวจสอบสาเหตุการเกิดเพลิงไหม้');
INSERT INTO `tbl_job` VALUES ('212', 'ช่างเทคนิคด้านวิศวกรรมการผลิต');
INSERT INTO `tbl_job` VALUES ('213', 'ช่างเทคนิคด้านหุ้นยนต์');
INSERT INTO `tbl_job` VALUES ('214', 'หัวหน้าคุมงานด้านเหมืองแร่');
INSERT INTO `tbl_job` VALUES ('215', 'หัวหน้าคุมงานด้านการผลิต');
INSERT INTO `tbl_job` VALUES ('216', 'ช่างเทคนิคควบคุมเครื่องจักรโรงงานผลิตพลังงานไฟฟ้า');
INSERT INTO `tbl_job` VALUES ('217', 'หัวหน้าคุมงานก่อสร้าง');
INSERT INTO `tbl_job` VALUES ('218', 'ช่างเทคนิคควบคุมเครื่องจักรไอน้ำและหม้อน้ำ');
INSERT INTO `tbl_job` VALUES ('219', 'ช่างเทคนิคควบคุมสถานีสูบน้ำ');
INSERT INTO `tbl_job` VALUES ('220', 'ช่างเทคนิคควบคุมเครื่องจักรโรงงานกำจัดขยะ');
INSERT INTO `tbl_job` VALUES ('221', 'ช่างเทคนิคควบคุมเครื่องจักรบำบัดน้ำเสีย');
INSERT INTO `tbl_job` VALUES ('222', 'ช่างเทคนิคควบคุมเครื่องจักรโรงงานแปรรูปทางเคมี');
INSERT INTO `tbl_job` VALUES ('223', 'ช่างเทคนิคควบคุมเครื่องจักรโรงงานกลั่นปิโตรเลียมและก๊าซธรรมชาติ');
INSERT INTO `tbl_job` VALUES ('224', 'ช่างเทคนิคควบคุมกระบวนการผลิตโลหะ');
INSERT INTO `tbl_job` VALUES ('225', 'ช่างเทคนิคควบคุมกระบวนการอื่นๆ ซึ่งมิได้จัดประเภทไว้ในที่อื่น');
INSERT INTO `tbl_job` VALUES ('226', 'ช่างเทคนิคควบคุมแผงควบคุมการผลิตเยื่อกระดาษและกระดาษ');
INSERT INTO `tbl_job` VALUES ('227', 'เจ้าหน้าที่เทคนิคด้านวิทยาศาสตร์สิ่งมีชีวิต (ยกเว้นแพทย์)');
INSERT INTO `tbl_job` VALUES ('228', 'เจ้าหน้าที่เทคนิคด้านการเกตษรและการประมง');
INSERT INTO `tbl_job` VALUES ('229', 'เจ้าหน้าที่เทคนิคด้านการป่าไม้');
INSERT INTO `tbl_job` VALUES ('230', 'ช่างเทคนิคหรือช่างเครื่องประจำเรือ');
INSERT INTO `tbl_job` VALUES ('231', 'วิศวกรประจำเรือ');
INSERT INTO `tbl_job` VALUES ('232', 'กัปตันเรือ');
INSERT INTO `tbl_job` VALUES ('233', 'เจ้าหน้าที่ประจำห้องบังคับการเรือและผู้นำร่อง');
INSERT INTO `tbl_job` VALUES ('234', 'ไต๋กงเรือ');
INSERT INTO `tbl_job` VALUES ('235', 'นักบินและผู้ประกอบวิชาชีพอื่นๆ ที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('236', 'ผู้ควบคุมการจราจรทางอากาศ');
INSERT INTO `tbl_job` VALUES ('237', 'วิศวกรความปลอดภัยด้านการจราจรทางอากาศ');
INSERT INTO `tbl_job` VALUES ('238', 'ช่างเทคนิคความปลอดภัยด้านการจราจรทางอากาศ');
INSERT INTO `tbl_job` VALUES ('239', 'เจ้าหน้าที่เทคนิคด้านการสร้างภาพทางการแพทย์และอุปกรณ์การบำบัดรักษาโรค');
INSERT INTO `tbl_job` VALUES ('240', 'เจ้าหน้าที่ถ่ายภาพรังสีเพื่อการวินิจฉัยทางการแพทย์');
INSERT INTO `tbl_job` VALUES ('241', 'เจ้าหน้าที่รังสีเทคนิคเพื่อการตรวจเต้านมด้วยเครื่องแมมโมแกรม');
INSERT INTO `tbl_job` VALUES ('242', 'เจ้าหน้าที่บำบัดด้วยรังสี');
INSERT INTO `tbl_job` VALUES ('243', 'เจ้าหน้าที่เอกเรย์ด้วยคลื่นแม่เหล็กไฟฟ้า (MRI)');
INSERT INTO `tbl_job` VALUES ('244', 'นักเทคโนโลยีการแพทย์นิวเคลียร์');
INSERT INTO `tbl_job` VALUES ('245', 'เจ้าหน้าที่อัลตราซาวนด์');
INSERT INTO `tbl_job` VALUES ('246', 'เจ้าหน้าที่ เทคนิคในห้องปฏิบัติการทางการแพทย์และพยาธิวิทยา');
INSERT INTO `tbl_job` VALUES ('247', 'เจ้าหน้าที่เทคนิคในธนาคารเลือด');
INSERT INTO `tbl_job` VALUES ('248', 'เจ้าหน้าที่เทคนิคด้านเชลล์วิทยา');
INSERT INTO `tbl_job` VALUES ('249', 'เจ้าหน้าที่เทคนิคด้านเภสัชกรรมและผู้ช่วย');
INSERT INTO `tbl_job` VALUES ('250', 'เจ้าหน้าที่เทคนิคด้านอุปกรณ์การแพทย์เทียมและฟันเทียม');
INSERT INTO `tbl_job` VALUES ('251', 'ผู้ประกอบวิชาชีพที่เกี่ยวข้องกับการพยาบาล');
INSERT INTO `tbl_job` VALUES ('252', 'ผู้ช่วยพยาบาล');
INSERT INTO `tbl_job` VALUES ('253', 'ผู้ประกอบวิชาชีพเกี่ยวข้องกบการผดุงครรภ์');
INSERT INTO `tbl_job` VALUES ('254', 'หมอตำแย');
INSERT INTO `tbl_job` VALUES ('255', 'ผู้ประกอบวิชาชีพที่เกี่ยวข้องกับแพทย์แผนโบราณและแพทย์ทางเลือก');
INSERT INTO `tbl_job` VALUES ('256', 'นักสมุนไพร');
INSERT INTO `tbl_job` VALUES ('257', 'หมอผี/หมอไสยศาสตร์');
INSERT INTO `tbl_job` VALUES ('258', 'ผู้ช่วยและผู้ประกอบวิชาชีพที่เกี่ยวข้องกับสัตวแพทย์');
INSERT INTO `tbl_job` VALUES ('259', 'ผู้ช่วยทันตแพทย์และนักทันตกรรมบำบัด');
INSERT INTO `tbl_job` VALUES ('260', 'เจ้าหน้าที่เวชระเบียนและเจ้าหน้าที่เทคนิคด้านข้อมูลสุขภาพ');
INSERT INTO `tbl_job` VALUES ('261', 'เจ้าหน้าที่ด้านสุขภาพของชุมชน');
INSERT INTO `tbl_job` VALUES ('262', 'ผู้ตรวจวัดสายตาและช่างประกอบแว่นตา');
INSERT INTO `tbl_job` VALUES ('263', 'เจ้าหน้าที่เทคนิคและผู้ช่วยด้านกายภาพบำบัด');
INSERT INTO `tbl_job` VALUES ('264', 'นักบำบัดโรคด้วยนวดแบบกดจุด');
INSERT INTO `tbl_job` VALUES ('265', 'ผู้ช่วยด้านการแพทย์');
INSERT INTO `tbl_job` VALUES ('266', 'ผู้ตรวจสอบด้านสิ่งแวดล้อม การทำงาน สุขภาพ และงานที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('267', 'เจ้าหน้าที่อนามัย');
INSERT INTO `tbl_job` VALUES ('268', 'เจ้าหน้าที่เทคนิคทางการแพทย์ฉุกเฉิน');
INSERT INTO `tbl_job` VALUES ('269', 'เจ้าหน้าที่ประจำรถพยาบาล');
INSERT INTO `tbl_job` VALUES ('270', 'เจ้าหน้าที่ผู้ช่วยแพทย์ฉุกเฉิน');
INSERT INTO `tbl_job` VALUES ('271', 'เจ้าหน้าที่เทคนิคด้านการวางยาชาและยาสลบ');
INSERT INTO `tbl_job` VALUES ('272', 'นักบำบัดโรคด้วยการจัดกระดูกสันหลัง (ไคโรแพรคติค)');
INSERT INTO `tbl_job` VALUES ('273', 'ที่ปรึกษาด้านการวางแผนครอบครัว');
INSERT INTO `tbl_job` VALUES ('274', 'นักบำบัดโรคด้วยการจัดกระดูกสันหลัง');
INSERT INTO `tbl_job` VALUES ('275', 'นักบำบัดโรคด้วยการจัดกระดูก');
INSERT INTO `tbl_job` VALUES ('276', 'นายหน้าที่หลักทรัพย์และการเงิน');
INSERT INTO `tbl_job` VALUES ('277', 'ตัวแทนจำหน่ายเงินตราต่างประเทศ');
INSERT INTO `tbl_job` VALUES ('278', 'นายหน้าซื้อขายหุ้น');
INSERT INTO `tbl_job` VALUES ('279', 'เจ้าหน้าที่สินเชื่อและให้กู้ยืม');
INSERT INTO `tbl_job` VALUES ('280', 'ผู้ประกอบวิชาชีพที่เกี่ยวข้องทางด้านบัญชี');
INSERT INTO `tbl_job` VALUES ('281', 'ผู้ประกอบวิชาชีพที่เกี่ยวข้องกับด้านสถิติ คณิตศาสตร์ และคณิตศาสตร์ประกันภัย');
INSERT INTO `tbl_job` VALUES ('282', 'ผู้ประเมินราคาและมูลค่าความเสียหาย');
INSERT INTO `tbl_job` VALUES ('283', 'ผู้ประเมินราคาอสังหาริมทรัพย์');
INSERT INTO `tbl_job` VALUES ('284', 'ผู้ประเมินราคาค่าสินไหมทดแทน');
INSERT INTO `tbl_job` VALUES ('285', 'ผู้ประเมินราคาด้านการประกันภัย');
INSERT INTO `tbl_job` VALUES ('286', 'ตัวแทนขายประกัน');
INSERT INTO `tbl_job` VALUES ('287', 'เจ้าหน้าที่รับประกันภัย');
INSERT INTO `tbl_job` VALUES ('288', 'ตัวแทนขายด้านการค้า');
INSERT INTO `tbl_job` VALUES ('289', 'ผู้จัดซื้อ');
INSERT INTO `tbl_job` VALUES ('290', 'นายหน้าทางการค้า');
INSERT INTO `tbl_job` VALUES ('291', 'ตัวแทนพิธีการศุลกากรและตัวแทนผู้รับจัดการขนส่งสินค้า');
INSERT INTO `tbl_job` VALUES ('292', 'นักวางแผนการจัดงานและการประชุม');
INSERT INTO `tbl_job` VALUES ('293', 'เจ้าหน้าที่จัดการประชุมและการแสดง');
INSERT INTO `tbl_job` VALUES ('294', 'ตัวแทนจัดหางานและผู้ทำสัญญาด้านแรงงานทั้งภาครัฐและเอกชน');
INSERT INTO `tbl_job` VALUES ('295', 'ตัวแทนอสังหาริมทรัพย์และผู้จัดการทรัพย์สิน');
INSERT INTO `tbl_job` VALUES ('296', 'นายหน้าซื้อขายสังหาริมทรัพย์');
INSERT INTO `tbl_job` VALUES ('297', 'พนักงานขายอสังหาริมทรัพย์');
INSERT INTO `tbl_job` VALUES ('298', 'ตัวแทนการให้บริการทางธุรกิจ');
INSERT INTO `tbl_job` VALUES ('299', 'พนักงานขายงานโฆษณา');
INSERT INTO `tbl_job` VALUES ('300', 'ตัวแทนธุรกิจด้านงานแสดงดนตรี/งานละคร');
INSERT INTO `tbl_job` VALUES ('301', 'ตัวแทนธุรกิจด้านงานประพันธ์');
INSERT INTO `tbl_job` VALUES ('302', 'หัวหน้าคุมงานในสำนักงาน');
INSERT INTO `tbl_job` VALUES ('303', 'เลขานุการด้านกฎหมาย');
INSERT INTO `tbl_job` VALUES ('304', 'เลขานุการด้านการบริหารและเลขานุการผู้บริหาร');
INSERT INTO `tbl_job` VALUES ('305', 'เจ้าหน้าที่บันทึกคำให้การในศาล');
INSERT INTO `tbl_job` VALUES ('306', 'เลขานุการด้านการแพทย์');
INSERT INTO `tbl_job` VALUES ('307', 'เจ้าหน้าที่ประจำด่านศุลกากรและบริเวณพรมแดน');
INSERT INTO `tbl_job` VALUES ('308', 'เจ้าหน้าที่ตรวจหนังสือเดินทาง');
INSERT INTO `tbl_job` VALUES ('309', 'เจ้าหน้าที่ตรวจคนเข้าเมือง');
INSERT INTO `tbl_job` VALUES ('310', 'เจ้าหน้าที่ศุลกากร');
INSERT INTO `tbl_job` VALUES ('311', 'เจ้าหน้าที่สรรพากรและสรรพสามิตของรัฐ');
INSERT INTO `tbl_job` VALUES ('312', 'เจ้าหน้าที่ตรวจสอบภาษี');
INSERT INTO `tbl_job` VALUES ('313', 'เจ้าหน้าที่ดูแลสิทธิประโยชน์ทางสังคมของรัฐ');
INSERT INTO `tbl_job` VALUES ('314', 'เจ้าหน้าที่ด้านการออกใบอนุญาตของรัฐ');
INSERT INTO `tbl_job` VALUES ('315', 'ตำรวจสืบสวนและนักสืบ');
INSERT INTO `tbl_job` VALUES ('316', 'สารวัตร');
INSERT INTO `tbl_job` VALUES ('317', 'พนักงานสืบสวนสอบสวน');
INSERT INTO `tbl_job` VALUES ('318', 'ผู้ประกอบวิชาชีพที่เกี่ยวกับด้านกฎระเบียนของรัฐ ซึ่งมิได้จัดประเภทไว้ในที่อื่นๆ');
INSERT INTO `tbl_job` VALUES ('319', 'นักสืบเอกชน');
INSERT INTO `tbl_job` VALUES ('320', 'ผู้ประกอบวิชาชีพที่เกี่ยวข้องกับกฎหมายและงานที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('321', 'เจ้าหน้าที่ตรวจสอบหลักฐานทะเบียนที่ดิน');
INSERT INTO `tbl_job` VALUES ('322', 'ผู้ประกอบวิชาชีพที่เกี่ยวกับงานสังคมสงเคราะห์');
INSERT INTO `tbl_job` VALUES ('323', 'ผู้ประกอบวิชาชีพที่เกี่ยวข้องกับศาสนา');
INSERT INTO `tbl_job` VALUES ('324', 'นักกรีฑาและนักกีฬา');
INSERT INTO `tbl_job` VALUES ('325', 'เจ้าหน้าที่และผู้ฝึกสอนกีฬา');
INSERT INTO `tbl_job` VALUES ('326', 'ผู้ฝึกสอนและผู้ดูแลโปรแกรมการสร้างสมรรถภาพของร่างการและการนันทนาการ');
INSERT INTO `tbl_job` VALUES ('327', 'ช่างถ่ายภาพ');
INSERT INTO `tbl_job` VALUES ('328', 'นักออกแบบตกแต่งภายในและมัณฑนากร');
INSERT INTO `tbl_job` VALUES ('329', 'ข่างเทคนิคดูแลห้องแสดงภาพ ห้องสมุดและพิพิธภัณฑ์');
INSERT INTO `tbl_job` VALUES ('330', 'หัวหน้าพ่อครัว/แม่ครัว');
INSERT INTO `tbl_job` VALUES ('331', 'ผู้ประกอบวิชาชีพที่เกี่ยวข้องด้านศิลปะ วัฒนธรรม ซึ่งมิได้จัดประเภทไว้ในที่อื่น');
INSERT INTO `tbl_job` VALUES ('332', 'นักแสดงแทน');
INSERT INTO `tbl_job` VALUES ('333', 'ช่างแต่งตัวนักแสดง');
INSERT INTO `tbl_job` VALUES ('334', 'ช่างสัก');
INSERT INTO `tbl_job` VALUES ('335', 'ช่างเทคนิคปฏิบัติการด้านเทคโนโลยีสารสนเทศและการสื่อสาร');
INSERT INTO `tbl_job` VALUES ('336', 'ช่างเทคนิคให้ความช่วยเหลือและแก้ปัญหาด้านเทคโนโลยีสารสนเทศและการสื่อสารกับผู้ใช้งาน');
INSERT INTO `tbl_job` VALUES ('337', 'ช่างเทคนิคด้านเครือข่ายและระบบคอมพิวเตอร์');
INSERT INTO `tbl_job` VALUES ('338', 'ช่างเทคนิคด้านเว็บไซต์');
INSERT INTO `tbl_job` VALUES ('339', 'ผู้บริหารเว็บไซต์');
INSERT INTO `tbl_job` VALUES ('340', 'ผู้ดูแลเว็บไซต์/เว็บมาสเตอร์');
INSERT INTO `tbl_job` VALUES ('341', 'ผู้เชี่ยวชาญด้านเว็บไซต์');
INSERT INTO `tbl_job` VALUES ('342', 'ช่างเทคนิคด้านการแพร่ภาพกระจายเสียงและโสตทัศนูปกรณ์');
INSERT INTO `tbl_job` VALUES ('343', 'ช่างกล้องถ่ายภาพยนตร์/ถ่ายวิดีโอ');
INSERT INTO `tbl_job` VALUES ('344', 'ช่างเทคนิควิศวกรโทรคมนาคม');
INSERT INTO `tbl_job` VALUES ('345', 'เสมียน');
INSERT INTO `tbl_job` VALUES ('346', 'เลขานุการทั่วไป');
INSERT INTO `tbl_job` VALUES ('347', 'พนักงานพิมพ์ดีด');
INSERT INTO `tbl_job` VALUES ('348', 'เจ้าหน้าที่จดชวเลข');
INSERT INTO `tbl_job` VALUES ('349', 'เจ้าหน้าที่บันทึกข้อมูล');
INSERT INTO `tbl_job` VALUES ('350', 'เจ้าพนักงานเร่งรัดหนี้สิน');
INSERT INTO `tbl_job` VALUES ('351', 'ผู้จัดนำเที่ยว');
INSERT INTO `tbl_job` VALUES ('352', 'พนักงานศูนย์บริการข้อมูลข่าวสาร');
INSERT INTO `tbl_job` VALUES ('353', 'พนักงานรับโทรศัพท์');
INSERT INTO `tbl_job` VALUES ('354', 'พนักงานควบคุมแผงเครื่องติดต่อทางโทรศัพท์');
INSERT INTO `tbl_job` VALUES ('355', 'พนักงานตอนรับของโรงแรม');
INSERT INTO `tbl_job` VALUES ('356', 'พนักงานเคาน์เตอร์ติดต่อสอบถาม');
INSERT INTO `tbl_job` VALUES ('357', 'พนักงานประชาสัมพันธ์');
INSERT INTO `tbl_job` VALUES ('358', 'พนักงานต้อนรับทั่วไป');
INSERT INTO `tbl_job` VALUES ('359', 'พนักงานสัมภาษณ์ในโครงการสำรวจและวิจัยตลาด');
INSERT INTO `tbl_job` VALUES ('360', 'เจ้าหน้าที่คัดกรองผู้มีสิทธิเข้ารับบริการ');
INSERT INTO `tbl_job` VALUES ('361', 'บุรุษไปรษณีย์');
INSERT INTO `tbl_job` VALUES ('362', 'พนักงานต้อนรับและบริการในการเดินทาง');
INSERT INTO `tbl_job` VALUES ('363', 'แอร์โฮสเตส');
INSERT INTO `tbl_job` VALUES ('364', 'พนักงานดูแลและเก็บค่าโดยสารยานพาหนะ');
INSERT INTO `tbl_job` VALUES ('365', 'มัคคุเทศก์');
INSERT INTO `tbl_job` VALUES ('366', 'พ่อครัว/แม่ครัว');
INSERT INTO `tbl_job` VALUES ('367', 'พนักงานเสิร์ฟอาหารและเครื่องดื่ม');
INSERT INTO `tbl_job` VALUES ('368', 'พนักงานผสมเครื่องดื่ม (บาร์เทนเดอร์)');
INSERT INTO `tbl_job` VALUES ('369', 'ช่างแต่งผม');
INSERT INTO `tbl_job` VALUES ('370', 'ช่างตัดผม');
INSERT INTO `tbl_job` VALUES ('371', 'ผู้เชี่ยวชาญด้านการดูแลเส้นผม');
INSERT INTO `tbl_job` VALUES ('372', 'ช่างเสริมสวยและผู้ปฏิบัติงานที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('373', 'ที่ปรึกษาด้านการลดน้ำหนักและกระชับสัดส่วน');
INSERT INTO `tbl_job` VALUES ('374', 'หัวหน้าคุมงานด้านการทำความสะอาดและงานแม่บ้านในสำนักงาน โรงแรมและสถานประกอบการอื่นๆ');
INSERT INTO `tbl_job` VALUES ('375', 'พนักงานดูแลงานบ้าน/แม่บ้าน');
INSERT INTO `tbl_job` VALUES ('376', 'พนักงานดูแลความเรียบร้อยของอาคารสถานที่');
INSERT INTO `tbl_job` VALUES ('377', 'นักการ/ภารโรง');
INSERT INTO `tbl_job` VALUES ('378', 'โหร ผู้ทำนายโชคชะตา และผู้ประกอบอาชีพที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('379', 'หมอดู');
INSERT INTO `tbl_job` VALUES ('380', 'นักโหราเลขศาสตร์');
INSERT INTO `tbl_job` VALUES ('381', 'คนรับใช้');
INSERT INTO `tbl_job` VALUES ('382', 'สัปเหร่อ');
INSERT INTO `tbl_job` VALUES ('383', 'เจ้าหน้าที่ฉีดยาศพ');
INSERT INTO `tbl_job` VALUES ('384', 'ช่างตัดแต่งขนสัตว์เลี้ยงและพนักงานดูแลสัตว์เลี้ยง');
INSERT INTO `tbl_job` VALUES ('385', 'ผู้ดูแลสวนสัตว์');
INSERT INTO `tbl_job` VALUES ('386', 'ครูสอนขับรถ');
INSERT INTO `tbl_job` VALUES ('387', 'พนักงานบริการส่วนบุคคล');
INSERT INTO `tbl_job` VALUES ('388', 'พนักงานต้อนรับชาย/หญิงในคลับ');
INSERT INTO `tbl_job` VALUES ('389', 'ผู้จำหน่ายสินค้าตามแผงลอยและตลาด');
INSERT INTO `tbl_job` VALUES ('390', 'ผู้จำหน่วยอาหารตามถนน');
INSERT INTO `tbl_job` VALUES ('391', 'พ่อค้า/แม่ค้าเร่ขายอาหาร');
INSERT INTO `tbl_job` VALUES ('392', 'เจ้าของร้านค้า');
INSERT INTO `tbl_job` VALUES ('393', 'ตัวแทนจำหน่ายหนังสือพิมพ์หรือนิตยสารต่างๆ');
INSERT INTO `tbl_job` VALUES ('394', 'หัวหน้าคุมงานในร้านค้า');
INSERT INTO `tbl_job` VALUES ('395', 'หัวหน้าคุมงานในซุปเปอร์มาร์เก็ต');
INSERT INTO `tbl_job` VALUES ('396', 'พนักงานช่วยขายในร้านค้า');
INSERT INTO `tbl_job` VALUES ('397', 'พนักงานในร้านค้าปลีก/ค้าส่ง');
INSERT INTO `tbl_job` VALUES ('398', 'พนักงานแคชเชียร์และเสมียนขายตั๋ว');
INSERT INTO `tbl_job` VALUES ('399', 'พนักงานแคชเชียร์ประจำสถานีบริการน้ำมันเชื้อเพลิง');
INSERT INTO `tbl_job` VALUES ('400', 'นายแบบและนางแบบแฟชั่นและผู้แสดงแบบอื่นๆ');
INSERT INTO `tbl_job` VALUES ('401', 'นายแบบและนางแบบงานโฆษณา');
INSERT INTO `tbl_job` VALUES ('402', 'นายแบบและนางแบบงานศิลปะ');
INSERT INTO `tbl_job` VALUES ('403', 'พนักงานสาธิตและขายสินค้า');
INSERT INTO `tbl_job` VALUES ('404', 'ผู้จำหน่วยสินค้าตามบ้าน');
INSERT INTO `tbl_job` VALUES ('405', 'พนักงานขายในศูนย์บริการลูกค้า');
INSERT INTO `tbl_job` VALUES ('406', 'ผู้จำหน่ายสินค้าในศูนย์บริการทางโทรศัพท์');
INSERT INTO `tbl_job` VALUES ('407', 'ผู้จำหน่ายสินค้าทางอินเตอร์เน็ต');
INSERT INTO `tbl_job` VALUES ('408', 'พนักงานบริการในสถานีบริการน้ำมันเชื้อเพลิง');
INSERT INTO `tbl_job` VALUES ('409', 'พนักงานประจำท่าจอดเรือ');
INSERT INTO `tbl_job` VALUES ('410', 'พนักงานเคาน์เตอร์บริการอาหาร');
INSERT INTO `tbl_job` VALUES ('411', 'ผู้จำหน่ายสินค้าอื่นๆ ซึ่งมิได้จัดประเภทไว้ในที่อื่นๆ');
INSERT INTO `tbl_job` VALUES ('412', 'ผู้ปฏิบัติงานดูแลเด็ก');
INSERT INTO `tbl_job` VALUES ('413', 'พี่เลี้ยงเด็ก');
INSERT INTO `tbl_job` VALUES ('414', 'ครูผู้ช่วยเด็กปฐมวัย');
INSERT INTO `tbl_job` VALUES ('415', 'ผู้ช่วยงานดูแลสุขภาพ');
INSERT INTO `tbl_job` VALUES ('416', 'เจ้าหน้าที่ช่วยงานพยาบาลตามคลินิกหรือโรงพยาบาล');
INSERT INTO `tbl_job` VALUES ('417', 'เจ้าหน้าที่ช่วยงานผดุงครรภ์ตามคลินิกหรือโรงพยาบาล');
INSERT INTO `tbl_job` VALUES ('418', 'เจ้าหน้าที่ช่วยดูแลผู้ป่วย');
INSERT INTO `tbl_job` VALUES ('419', 'ผู้ดูแลส่วนบุคคลตามบ้าน');
INSERT INTO `tbl_job` VALUES ('420', 'ผู้ดูแลส่วนบุคคลด้านสุขภาพซึ่งมิได้จัดประเภทไว้ในที่อื่น');
INSERT INTO `tbl_job` VALUES ('421', 'เจ้าหน้าที่เจาะเลือด');
INSERT INTO `tbl_job` VALUES ('422', 'พนักงานดับเพลิง');
INSERT INTO `tbl_job` VALUES ('423', 'พนักงานดับไฟป่า');
INSERT INTO `tbl_job` VALUES ('424', 'เจ้าหน้าที่ตำรวจ');
INSERT INTO `tbl_job` VALUES ('425', 'ผู้คุมนักโทษ');
INSERT INTO `tbl_job` VALUES ('426', 'พัศดี');
INSERT INTO `tbl_job` VALUES ('427', 'พนักงานรักษาความปลอดภัย');
INSERT INTO `tbl_job` VALUES ('428', 'ยามรักษาการณ์');
INSERT INTO `tbl_job` VALUES ('429', 'ผู้ให้บริการด้านการป้องกันภัย ซึ่งมิได้จัดประเภทไว้ในที่อื่นๆ');
INSERT INTO `tbl_job` VALUES ('430', 'เจ้าหน้าที่ดูแลสัตว์ป่า');
INSERT INTO `tbl_job` VALUES ('431', 'ผู้ดูแลสวนสัตว์');
INSERT INTO `tbl_job` VALUES ('432', 'ผู้ปลูกพืชไร่และพืชผัก');
INSERT INTO `tbl_job` VALUES ('433', 'ทำไร่');
INSERT INTO `tbl_job` VALUES ('434', 'ชาวนาปลูกข้าว');
INSERT INTO `tbl_job` VALUES ('435', 'ผู้ปลูกไม้ยืนต้นและไม้ผล');
INSERT INTO `tbl_job` VALUES ('436', 'คนงานกรีดยาง');
INSERT INTO `tbl_job` VALUES ('437', 'ผู้ปลูกยางพารา');
INSERT INTO `tbl_job` VALUES ('438', 'ผู้ปลูกพืชสวน ไม้ดอกไม้ประดับ และพืชในเรือนเพาะชำ');
INSERT INTO `tbl_job` VALUES ('439', 'ผู้ปลูกไม้ดอกไม้ประดับ');
INSERT INTO `tbl_job` VALUES ('440', 'นักออกแบบตกแต่งสวน');
INSERT INTO `tbl_job` VALUES ('441', 'เพาะต้นไม้ขาย');
INSERT INTO `tbl_job` VALUES ('442', 'ผู้เพาะเห็ด');
INSERT INTO `tbl_job` VALUES ('443', 'คนงานเก็บผลไม้');
INSERT INTO `tbl_job` VALUES ('444', 'ผู้ปลูกพืชแบบผสมผสาน');
INSERT INTO `tbl_job` VALUES ('445', 'ผู้เลี้ยงปศุสัตว์และผลิตภัณฑ์นม');
INSERT INTO `tbl_job` VALUES ('446', 'ทำฟาร์มนม');
INSERT INTO `tbl_job` VALUES ('447', 'ผู้เลี้ยงสัตว์ปี ก');
INSERT INTO `tbl_job` VALUES ('448', 'ผู้ผสมพันธุ์สัตว์ปี ก');
INSERT INTO `tbl_job` VALUES ('449', 'ผู้ทำฟาร์มสัตว์ปี ก');
INSERT INTO `tbl_job` VALUES ('450', 'ผู้เลี้ยงผึ้งและไหม');
INSERT INTO `tbl_job` VALUES ('451', 'ผู้เลี้ยงสัตว์เพื่อการค้าขาย ซึ่งมิได้จัดประเภทไว้ในที่อื่น');
INSERT INTO `tbl_job` VALUES ('452', 'ผู้เลี้ยงนกกระจอกเทศ');
INSERT INTO `tbl_job` VALUES ('453', 'ผู้ปลูกพืชร่วมกับการเลี้ยงสัตว์');
INSERT INTO `tbl_job` VALUES ('454', 'ผู้ปฏิบัติงานด้านการป่าไม้และงานอื่นที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('455', 'คนเผาถ่าน');
INSERT INTO `tbl_job` VALUES ('456', 'ผู้สำรวจทรัพยากรป่าไม้');
INSERT INTO `tbl_job` VALUES ('457', 'คนงานฝีมือด้านการป่าไม้');
INSERT INTO `tbl_job` VALUES ('458', 'ผู้ปฏิบัติงานด้านการเพาะเลี้ยงสัตว์น้ำ');
INSERT INTO `tbl_job` VALUES ('459', 'ผู้ทำฟาร์มสัตว์น้ำ');
INSERT INTO `tbl_job` VALUES ('460', 'ผู้เลี้ยงหอยนางรม');
INSERT INTO `tbl_job` VALUES ('461', 'ผู้ปฏิบัติงานด้านการประมงน้ำจืดและประมงชายฝั่งทะเล');
INSERT INTO `tbl_job` VALUES ('462', 'กัปตันเรือประมงชายฝั่ง');
INSERT INTO `tbl_job` VALUES ('463', 'ชาวประมงพื้นบ้าน');
INSERT INTO `tbl_job` VALUES ('464', 'ชาวประมงทะเลน้ำลึก');
INSERT INTO `tbl_job` VALUES ('465', 'กัปตันเรือประมงทะเลน้ำลึก');
INSERT INTO `tbl_job` VALUES ('466', 'กัปตันเรือลากอวน');
INSERT INTO `tbl_job` VALUES ('467', 'ผู้ปฏิบัติงานด้านล่าสัตว์และวางกับดักสัตว์ต่างๆ');
INSERT INTO `tbl_job` VALUES ('468', 'ผู้ปฏิบัติงานด้านการปลูกพืชเพื่อการดำรงชีพ');
INSERT INTO `tbl_job` VALUES ('469', 'ผู้ปฏิบัติงานด้านการเลี้ยงสัตว์เพื่อการดำรงชีพ');
INSERT INTO `tbl_job` VALUES ('470', 'ผู้ปฏิบัติงานด้านการปลูกพืชร่วมกับการเลี้ยงสัตว์เพื่อการดำรงชีพ');
INSERT INTO `tbl_job` VALUES ('471', 'ผู้ปฏิบัติงานด้านการประมง ล่าสัตว์และเก็บพืชผลเพื่อการดำรงชีพ');
INSERT INTO `tbl_job` VALUES ('472', 'คนหาของป่า');
INSERT INTO `tbl_job` VALUES ('473', 'คนงมหาของใต้น้ำเพื่อการดำรงชีพ');
INSERT INTO `tbl_job` VALUES ('474', 'ช่างก่อสร้างที่อยู่อาศัย');
INSERT INTO `tbl_job` VALUES ('475', 'ช่างก่ออิฐและผู้ปฏิบัติงานที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('476', 'ช่างหิน ตัดหิน เจาะสกัดหิน และแกะหิน');
INSERT INTO `tbl_job` VALUES ('477', 'ช่างขัดเงาหิน');
INSERT INTO `tbl_job` VALUES ('478', 'ช่างปูกระเบื้องและผนัง');
INSERT INTO `tbl_job` VALUES ('479', 'ช่างหล่อเทคอนกรีต ตกแต่งผิวซีเมนต์ และผู้ปฏิบัติงานที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('480', 'ช่างทำพื้นหินขัด');
INSERT INTO `tbl_job` VALUES ('481', 'ช่างไม้');
INSERT INTO `tbl_job` VALUES ('482', 'ช่างต่อเรือไม้');
INSERT INTO `tbl_job` VALUES ('483', 'ช่างก่อสร้างโครงสร้างอาคาร สิ่งปลูกสร้าง และผู้ปฏิบัติงานที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('484', 'ช่างรื้อถอนอาคาร');
INSERT INTO `tbl_job` VALUES ('485', 'ช่างมุ้งหลังคา');
INSERT INTO `tbl_job` VALUES ('486', 'ช่างซ่อมหลังคา');
INSERT INTO `tbl_job` VALUES ('487', 'ช่างติดตั้งหลังคาโลหะ');
INSERT INTO `tbl_job` VALUES ('488', 'ช่างปูพื้นและกระเบื้อง');
INSERT INTO `tbl_job` VALUES ('489', 'ช่างปูพรม');
INSERT INTO `tbl_job` VALUES ('490', 'ช่างฉาบปูนและตกแต่งงานปูน');
INSERT INTO `tbl_job` VALUES ('491', 'ช่างติดตั้งฉนวน');
INSERT INTO `tbl_job` VALUES ('492', 'ช่างติดกระจก');
INSERT INTO `tbl_job` VALUES ('493', 'ช่างประปาและวางท่อ');
INSERT INTO `tbl_job` VALUES ('494', 'ช่างติดตั้งท่อระบายน้ำ รางน้ำ และท่อโลหะ');
INSERT INTO `tbl_job` VALUES ('495', 'ช่างซ่อมท่อ');
INSERT INTO `tbl_job` VALUES ('496', 'ช่างเครื่องระบบปรับอากาศและระบบความเย็น');
INSERT INTO `tbl_job` VALUES ('497', 'ช่างทาสีและปฏิบัติงานที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('498', 'ช่างปิดวอลเปเปอร์หรือผ้าลงบนพนัก/เพดาน');
INSERT INTO `tbl_job` VALUES ('499', 'ช่างพ่นสีขัดเงา');
INSERT INTO `tbl_job` VALUES ('500', 'ช่างทำความสะอาดโครงสร้างอาคาร สิ่งปลูกสร้าง');
INSERT INTO `tbl_job` VALUES ('501', 'ช่างทำแบบหล่อโลหะและแกนแบบหล่อโลหะ');
INSERT INTO `tbl_job` VALUES ('502', 'ช่างเชื่อมและช่างตัดโลหะด้วยเปลวไฟ');
INSERT INTO `tbl_job` VALUES ('503', 'ช่างทำเครื่องทองเหลือง');
INSERT INTO `tbl_job` VALUES ('504', 'ช่างโลหะแผ่น');
INSERT INTO `tbl_job` VALUES ('505', 'ช่างทำผลิตภัณฑ์โลหะแผนสำหรับให้ช่างมุงหลังคาใช้งานและติดตั้ง');
INSERT INTO `tbl_job` VALUES ('506', 'ช่างเตรียมและติดตั้งโครงสร้างโลหะ');
INSERT INTO `tbl_job` VALUES ('507', 'ช่างติดตั้งเครื่องยกหรือสายเคเบิล');
INSERT INTO `tbl_job` VALUES ('508', 'ช่างเหล็ก ช่างตีเหล็ก และช่างคุมเครื่องอัดขึ้นรูปโลหะ');
INSERT INTO `tbl_job` VALUES ('509', 'ช่างทำกุญแจ');
INSERT INTO `tbl_job` VALUES ('510', 'ช่างปืน');
INSERT INTO `tbl_job` VALUES ('511', 'ช่างปรับตั้งและใช้เครื่องกลงานโลหะ');
INSERT INTO `tbl_job` VALUES ('512', 'ช่างกลึงโลหะ');
INSERT INTO `tbl_job` VALUES ('513', 'ช่างคุมเครื่องหล่อโลหะ');
INSERT INTO `tbl_job` VALUES ('514', 'ช่างคุมเครื่องกลึงโลหะ');
INSERT INTO `tbl_job` VALUES ('515', 'ช่างคุมเครื่องคว้านโลหะ');
INSERT INTO `tbl_job` VALUES ('516', 'ช่างขัดเงาโลหะ ช่างเจียระไนโลหะ และช่างลับเครื่องมือ');
INSERT INTO `tbl_job` VALUES ('517', 'ช่างลับมีด');
INSERT INTO `tbl_job` VALUES ('518', 'ช่างเครื่องและช่างซ่อมเครื่องยนต์ยานยนต์');
INSERT INTO `tbl_job` VALUES ('519', 'ช่างเครื่องและช่างปรับเครื่องยนต์อากาศยาน');
INSERT INTO `tbl_job` VALUES ('520', 'วิศวกรบำรุงรักษาโครงสร้างอากาศยาน');
INSERT INTO `tbl_job` VALUES ('521', 'วิศวกรบำรุงรักษาเครื่องยนต์อากาศยาน');
INSERT INTO `tbl_job` VALUES ('522', 'ช่างซ่อมเฮลิคอปเตอร์');
INSERT INTO `tbl_job` VALUES ('523', 'ช่างเครื่องและช่างปรับเครื่องจักรกลทางการเกษตรหรืออุตสาหกรรม');
INSERT INTO `tbl_job` VALUES ('524', 'ช่างซ่อมรถจักรยานและผู้ปฏิบัติงานที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('525', 'ช่างซ่อมรถเข็นเด็กทารก');
INSERT INTO `tbl_job` VALUES ('526', 'ช่างซ่อมรถเข็นสำหรับคนป่วยหรือคนพิการ');
INSERT INTO `tbl_job` VALUES ('527', 'ช่างทำและซ่อมเครื่องมือที่มีความเที่ยงตรงแม่นยํา');
INSERT INTO `tbl_job` VALUES ('528', 'ช่างซ่อมและทำนาฬิกา');
INSERT INTO `tbl_job` VALUES ('529', 'ช่างทำและซ่อมเครื่องมือที่ใช้ในการพยากรณ์อากาศ');
INSERT INTO `tbl_job` VALUES ('530', 'ช่างซ่อมอุปกรณ์ถ่ายภาพ');
INSERT INTO `tbl_job` VALUES ('531', 'ช่างทำเครื่องดนตรีและปรับเสียงดนตรี');
INSERT INTO `tbl_job` VALUES ('532', 'ช่างปรับเสียงเปียโน');
INSERT INTO `tbl_job` VALUES ('533', 'ช่างทำเสียงดนตรีประเภทสาย');
INSERT INTO `tbl_job` VALUES ('534', 'ช่างทำเครื่องเพชรพลอยและรูปพรรณ และโลหะมีค่า');
INSERT INTO `tbl_job` VALUES ('535', 'ช่างทอง');
INSERT INTO `tbl_job` VALUES ('536', 'ช่างฝังอัญมณี');
INSERT INTO `tbl_job` VALUES ('537', 'ช่างเงิน');
INSERT INTO `tbl_job` VALUES ('538', 'ช่างลงยาเครื่องเพชรพลอยและรูปพรรณ');
INSERT INTO `tbl_job` VALUES ('539', 'ช่างทำเครื่องปั้นดินเผาและผู้ปฏิบัติงานที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('540', 'ช่างทำเครื่องแกว ช่างตัด ช่างเจียระไน และช่างตกแต่งเครื่องแก้ว');
INSERT INTO `tbl_job` VALUES ('541', 'ช่างเขียนเครื่องหมาย ช่างลงสี ช่างแกะสลัก และช่างกับลายแก้ว');
INSERT INTO `tbl_job` VALUES ('542', 'ช่างเขียนป้ายหรือเครื่องหมาย');
INSERT INTO `tbl_job` VALUES ('543', 'ช่างเคลือบแก้ว');
INSERT INTO `tbl_job` VALUES ('544', 'ช่างงานหัตกรรมไม้ เครื่องจักรสาน และวัสดุที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('545', 'ช่างทำเฟอร์นิเจอร์สาน');
INSERT INTO `tbl_job` VALUES ('546', 'ช่างทำตะกร้า');
INSERT INTO `tbl_job` VALUES ('547', 'ช่างงานหัตกรรมสิ่งทอ เครื่องหนัง และวัสดุที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('548', 'ช่างทอเสือผ้า');
INSERT INTO `tbl_job` VALUES ('549', 'ช่างงานหัตกรรม ซึ่งมิได้จัดประเภทไว้ในที่อื่น');
INSERT INTO `tbl_job` VALUES ('550', 'ช่างเกาะสลักหิน');
INSERT INTO `tbl_job` VALUES ('551', 'ช่างเทคนิคก่อนงานพิมพ์');
INSERT INTO `tbl_job` VALUES ('552', 'ช่างประกอบฟิล์ม');
INSERT INTO `tbl_job` VALUES ('553', 'ช่างจัดพิมพ์ด้วยคอมพิวเตอร์ (Desktop publishing)');
INSERT INTO `tbl_job` VALUES ('554', 'ช่างเทคนิคงานก่อนงานพิมพ์อิเล็กทรอนิกส์');
INSERT INTO `tbl_job` VALUES ('555', 'ช่างทำเพลตงานพิมพ์สกรีน');
INSERT INTO `tbl_job` VALUES ('556', 'ช่างทำแม่พิมพ์งานพิมพ์');
INSERT INTO `tbl_job` VALUES ('557', 'ช่างเรียงพิมพ์');
INSERT INTO `tbl_job` VALUES ('558', 'ช่างสร้างลายด้วยแสง');
INSERT INTO `tbl_job` VALUES ('559', 'ช่างพิมพ์');
INSERT INTO `tbl_job` VALUES ('560', 'ช่างตกแต่งงานพิมพ์และเข้าเล่ม');
INSERT INTO `tbl_job` VALUES ('561', 'พนักงานเครื่องตัดกระดาษ');
INSERT INTO `tbl_job` VALUES ('562', 'ช่างเดินสายไฟภายในอาคารและอุปกรณ์ไฟฟ้าที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('563', 'ช่างไฟฟ้า');
INSERT INTO `tbl_job` VALUES ('564', 'ช่างซ่อมไฟฟ้าประจำอาคาร');
INSERT INTO `tbl_job` VALUES ('565', 'ช่างเครื่องและช่างปรับอุปกรณ์ไฟฟ้า');
INSERT INTO `tbl_job` VALUES ('566', 'ช่างไฟฟ้ายานยนต์');
INSERT INTO `tbl_job` VALUES ('567', 'ช่างพันไดนาโม');
INSERT INTO `tbl_job` VALUES ('568', 'ช่างซ่อมลิฟต์');
INSERT INTO `tbl_job` VALUES ('569', 'ช่างติดตั้งและซ่อมสายส่งกระแสไฟฟ้า');
INSERT INTO `tbl_job` VALUES ('570', 'ช่างเครื่องและผู้ให้บริการด้านอุปกรณ์อิเล็กทรอนิกส์');
INSERT INTO `tbl_job` VALUES ('571', 'วิศวกรบำรุงรักษาอุปกรณ์ไฟฟ้าและอิเล็กทรอนิกส์อากาศยาน');
INSERT INTO `tbl_job` VALUES ('572', 'ช่างเทคนิคเครื่องถ่ายเอกสาร');
INSERT INTO `tbl_job` VALUES ('573', 'ช่างติดตั้งและผู้ให้บริการด้านอุปกรณ์เทคโนโลยีสารสนเทศและการสื่อสาร');
INSERT INTO `tbl_job` VALUES ('574', 'ช่างติดตั้งโทรศัพท์');
INSERT INTO `tbl_job` VALUES ('575', 'ผู้ฆ่าชำแหละเนื้อสัตว์และสัตว์น้ำ และผู้จัดเตรียมอาหารที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('576', 'คนขายปลา');
INSERT INTO `tbl_job` VALUES ('577', 'ผู้ทำขนมปัง ขนมเค้ก ขนมหวาน และลูกกวาด');
INSERT INTO `tbl_job` VALUES ('578', 'ผู้ผลิตผลิตภัณฑ์นม');
INSERT INTO `tbl_job` VALUES ('579', 'ผู้ถนอมผลไม้ พืชผัก และผู้ถนอมอาหารที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('580', 'ผู้ชิมรสและจัดระดับชั้นคุณภาพของอาหารและเครื่องดื่ม');
INSERT INTO `tbl_job` VALUES ('581', 'ผู้เตรียมใบยาสูบและผลิตผลิตภัณฑ์ยาสูบ');
INSERT INTO `tbl_job` VALUES ('582', 'ช่างอัดน้ำยาและอบไม้');
INSERT INTO `tbl_job` VALUES ('583', 'ช่างควบคุมเตาอบไม้');
INSERT INTO `tbl_job` VALUES ('584', 'ช่างทำเฟอร์นิเจอร์ไม้และผู้ปฏิบัติงานที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('585', 'ช่างทำตู้');
INSERT INTO `tbl_job` VALUES ('586', 'ช่างทำเกวียน');
INSERT INTO `tbl_job` VALUES ('587', 'ช่างปรับตั้งและใช้เครื่องจักรงานไม้');
INSERT INTO `tbl_job` VALUES ('588', 'ช่างเครื่องแกะสลักไม้');
INSERT INTO `tbl_job` VALUES ('589', 'ช่างเครื่องผลิตเฟอร์นิเจอร์ไม้');
INSERT INTO `tbl_job` VALUES ('590', 'ช่างตัดเย็บเสื้อผ้า ช่างทำเสื้อผ้าขนสัตว์ และช่างทำหมวก');
INSERT INTO `tbl_job` VALUES ('591', 'ผู้คัดคุณภาพหนังเฟอร์นิเจอร์');
INSERT INTO `tbl_job` VALUES ('592', 'ช่างสร้างแบบและตัดวัสดุเพื่อผลิตเครื่องแต่งกายและสิ่งของที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('593', 'ช่างสร้างแบบเครื่องแต่งกาย');
INSERT INTO `tbl_job` VALUES ('594', 'ช่างตัดเครื่องแต่งกาย');
INSERT INTO `tbl_job` VALUES ('595', 'ช่างเย็บ ช่างปัก และผู้ปฏิบัติงานที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('596', 'ช่างทำร่ม');
INSERT INTO `tbl_job` VALUES ('597', 'ช่างหุ้มเบาะและผู้ปฏิบัติงานที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('598', 'ช่างหุ้มอุปกรณ์ทางศัลยศาสตร์กระดูก');
INSERT INTO `tbl_job` VALUES ('599', 'ช่างทำฟูกที่นอน');
INSERT INTO `tbl_job` VALUES ('600', 'ช่างตกแต่งหนังสัตว์ ช่างฟอกหนัง และช่างถากหนังขูดขนสัตว์');
INSERT INTO `tbl_job` VALUES ('601', 'ช่างย้อมหนังสัตว์');
INSERT INTO `tbl_job` VALUES ('602', 'ช่างทำรองเท้าและผู้ปฏิบัติงานที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('603', 'ช่างซ่อมรองเท้า');
INSERT INTO `tbl_job` VALUES ('604', 'ช่างทำอานม้า');
INSERT INTO `tbl_job` VALUES ('605', 'ผู้ปฏิบัติงานใต้น้ำ');
INSERT INTO `tbl_job` VALUES ('606', 'นักประดาน้ำกู้ภัย');
INSERT INTO `tbl_job` VALUES ('607', 'คนเก็บหอยนางรม');
INSERT INTO `tbl_job` VALUES ('608', 'ผู้ปฏิบัติด้านวัตถุระเบิดและผู้ปฏิบัติงานจุดระเบิด');
INSERT INTO `tbl_job` VALUES ('609', 'เจ้าหน้าที่จุดระเบิดในเหมืองแร่และเหมืองหิน');
INSERT INTO `tbl_job` VALUES ('610', 'ผู้คัดคุณภาพและทดสอบผลิตภัณฑ์ (ยกเว้นอาหารและเครื่องดื่ม)');
INSERT INTO `tbl_job` VALUES ('611', 'ผู้รมยาและกำจัดแมลงและสัตว์ศัตรูพืช');
INSERT INTO `tbl_job` VALUES ('612', 'ผู้รมยากำจัดปลวก/แมลงสาป');
INSERT INTO `tbl_job` VALUES ('613', 'คนจัดดอกไม้');
INSERT INTO `tbl_job` VALUES ('614', 'ช่างตัดแต่งเลนส์ชนิดใช้ในทางทัศนศาสตร์');
INSERT INTO `tbl_job` VALUES ('615', 'ผู้ปฏิบัติงานในเหมืองแร่และเหมืองหิน');
INSERT INTO `tbl_job` VALUES ('616', 'ผู้ควบคุมเครื่องจักรแบบต่อเนื่องในเหมืองแร่');
INSERT INTO `tbl_job` VALUES ('617', 'ผู้ควบคุมเครื่องจักรขุดเจาะในการทำเหมืองแร่');
INSERT INTO `tbl_job` VALUES ('618', 'ผู้ควบคุมเครื่องจักรขนาดใหญ่ในการทำเหมืองแร่');
INSERT INTO `tbl_job` VALUES ('619', 'ผู้ควบคุมเครื่องยกขนาดใหญ่ในเหมืองแร่');
INSERT INTO `tbl_job` VALUES ('620', 'ผู้ควบคุมเครื่องจักรโรงงานในเหมืองแร่');
INSERT INTO `tbl_job` VALUES ('621', 'พนักงานขุดเจาะด้วยเครื่องจักรในเหมืองแร่');
INSERT INTO `tbl_job` VALUES ('622', 'ผู้ควบคุมเครื่องจักรโรงงานแปรรูปแร่และหิน');
INSERT INTO `tbl_job` VALUES ('623', 'คนร่อนทอง');
INSERT INTO `tbl_job` VALUES ('624', 'ผู้ควบคุมเครื่องจักรขุดเจาะบ่อและปฏิบัติงานที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('625', 'ผู้ควบคุมเครื่องจักรเจาะคว้าน');
INSERT INTO `tbl_job` VALUES ('626', 'ผู้ควบคุมเครื่องเจาะบ่อน้ำมันหรือก๊าซ');
INSERT INTO `tbl_job` VALUES ('627', 'ผู้ควบคุมเครื่องจักรขุดเจาะขนาดใหญ่');
INSERT INTO `tbl_job` VALUES ('628', 'ผู้ควบคุมเครื่องจักรผลิตผลิตภัณฑ์ซีเมนต์ หิน และแร่อื่นๆ');
INSERT INTO `tbl_job` VALUES ('629', 'ผู้ควบคุมเครื่องจักรผลิตคอนกรีตหล่อสำเร็จรูป');
INSERT INTO `tbl_job` VALUES ('630', 'ผู้ควบคุมเครื่องจักรผลิตผลิตภัณฑ์คอนกรีต');
INSERT INTO `tbl_job` VALUES ('631', 'ผู้ควบคุมเครื่องจักรโรงงานแปรรูปโลหะ');
INSERT INTO `tbl_job` VALUES ('632', 'ผู้ควบคุมเครื่องจักรตกแต่ง ชุบ และเคลือบผิวโลหะ');
INSERT INTO `tbl_job` VALUES ('633', 'ผู้ควบคุมเครื่องจักรโรงงานและเครื่องจักรผลิตผลิตภัณฑ์เคมี');
INSERT INTO `tbl_job` VALUES ('634', 'ผู้ควบคุมเครื่องจักรผลิตผลิตภัณฑ์ทางเภสัชกรรมและเครื่องประเทืองโฉม');
INSERT INTO `tbl_job` VALUES ('635', 'ผู้ควบคุมเครื่องจักรผลิตผลิตภัณฑ์ด้านการถ่ายภาพ');
INSERT INTO `tbl_job` VALUES ('636', 'ช่างเทคนิคในห้องมือสำหรับล้างรูป');
INSERT INTO `tbl_job` VALUES ('637', 'ผู้ควบคุมเครื่องล้างฟิล์ม');
INSERT INTO `tbl_job` VALUES ('638', 'เจ้าหน้าที่ล้างอัดรูป');
INSERT INTO `tbl_job` VALUES ('639', 'เจ้าหน้าที่อัดขยายภาพ');
INSERT INTO `tbl_job` VALUES ('640', 'ผู้ควบคุมเครื่องจักรผลิตผลิตภัณฑ์ยาง');
INSERT INTO `tbl_job` VALUES ('641', 'ผู้ควบคุมเครื่องจักรผลิตผลิตภัณฑ์พลาสติก');
INSERT INTO `tbl_job` VALUES ('642', 'พนักงานดึงเส้นใยแก้ว');
INSERT INTO `tbl_job` VALUES ('643', 'ผู้ควบคุมเครื่องจักรผลิตผลิตภัณฑ์กระดาษ');
INSERT INTO `tbl_job` VALUES ('644', 'ผู้ควบคุมเครื่องจักรจัดเตรียมเส้นใย ปั่น และกรอเส้นใย');
INSERT INTO `tbl_job` VALUES ('645', 'ผู้ควบคุมเครื่องจักรทอผ้าและเครื่องจักรถักนิต');
INSERT INTO `tbl_job` VALUES ('646', 'ผู้ควบคุมเครื่องจักรผลิตตาข่าย');
INSERT INTO `tbl_job` VALUES ('647', 'ผู้ควบคุมเครื่องจักรเย็บผ้า');
INSERT INTO `tbl_job` VALUES ('648', 'ผู้ควบคุมเครื่องจักร ปักลวดลาย');
INSERT INTO `tbl_job` VALUES ('649', 'ผู้ควบคุมเครื่องจักรฟอก ย้อม และทำความสะอาดเส้นใย');
INSERT INTO `tbl_job` VALUES ('650', 'ผู้ควบคุมเครื่องจักรจัดเตรียมขนสัตว์และหนังฟอก');
INSERT INTO `tbl_job` VALUES ('651', 'ผู้ควบคุมเครื่องจักรผลิตรองเท้า');
INSERT INTO `tbl_job` VALUES ('652', 'ผู้ควบคุมเครื่องจักรด้านการซักรีด');
INSERT INTO `tbl_job` VALUES ('653', 'ผู้ควบคุมเครื่องจักรผลิตผลิตภัณฑ์สิ่งทอ ขนสัตว์ และหนังฟอก ซึ่งมิได้จัดประเภทไว้ในที่อื่น');
INSERT INTO `tbl_job` VALUES ('654', 'ผู้ควบคุมเครื่องจักรสร้างแบบ (pattern)');
INSERT INTO `tbl_job` VALUES ('655', 'ผู้ควบคุมเครื่องจักรผลิตหมวก');
INSERT INTO `tbl_job` VALUES ('656', 'ผู้ควบคุมเครื่องจักรผลิตเปีย');
INSERT INTO `tbl_job` VALUES ('657', 'ผู้ควบคุมเครื่องจักรผลิตเต็นท์');
INSERT INTO `tbl_job` VALUES ('658', 'ผู้ควบคุมเครื่องจักรผลิตผลิตภัณฑ์อาหารและผลิตภัณฑ์ที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('659', 'ผู้ควบคุมเครื่องจักรผลิตบุหรี่');
INSERT INTO `tbl_job` VALUES ('660', 'ผู้ควบคุมเครื่องจักรโรงงานผลิตเยื่อกระดาษและกระดาษ');
INSERT INTO `tbl_job` VALUES ('661', 'ผู้ควบคุมเครื่องจักรแปรรูปไม้');
INSERT INTO `tbl_job` VALUES ('662', 'ผู้ปฏิบัติงานเครื่องจักรโรงงานผลิตแก้วและเซรามิก');
INSERT INTO `tbl_job` VALUES ('663', 'ผู้ควบคุมเตาเผาอิฐและกระเบื้อง');
INSERT INTO `tbl_job` VALUES ('664', 'ผู้ควบคุมเครื่องจักรผสมดินเหนียว');
INSERT INTO `tbl_job` VALUES ('665', 'ผู้ควบคุมเครื่องปั้นดินเผาและเครื่องพอร์ชเลน');
INSERT INTO `tbl_job` VALUES ('666', 'ผู้ปฏิบัติงานเครื่องจักรไอน้ำและหม้อน้ำ');
INSERT INTO `tbl_job` VALUES ('667', 'ผู้ปฏิบัติงานเครื่องจักรที่ใช้ในการห่อและบรรจุผลิตภัณฑ์ การบรรจุขวด และการติดฉลาก');
INSERT INTO `tbl_job` VALUES ('668', 'ผู้ควบคุมเครื่องจักรฟั่นต่อสายเคเบิลและเชือก');
INSERT INTO `tbl_job` VALUES ('669', 'ผู้ประกอบเครื่องจักรกล');
INSERT INTO `tbl_job` VALUES ('670', 'พนักงานประกอบกระปุกเกียร์');
INSERT INTO `tbl_job` VALUES ('671', 'พนักงานประกอบเครื่องยนต์');
INSERT INTO `tbl_job` VALUES ('672', 'พนักงานประกอบยานยนต์');
INSERT INTO `tbl_job` VALUES ('673', 'พนักงานติดตั้งเครื่องยนต์');
INSERT INTO `tbl_job` VALUES ('674', 'พนักงานประกอบอากาศยาน');
INSERT INTO `tbl_job` VALUES ('675', 'พนักงานประกอบเครื่องกังหัน');
INSERT INTO `tbl_job` VALUES ('676', 'ผู้ประกอบอุปกรณ์ไฟฟ้าและอิเล็กทรอนิกส์');
INSERT INTO `tbl_job` VALUES ('677', 'พนักงานประกอบโทรศัพท์');
INSERT INTO `tbl_job` VALUES ('678', 'พนักงานประกอบโทรทัศน์');
INSERT INTO `tbl_job` VALUES ('679', 'พนักงานประกอบนาฬิกา');
INSERT INTO `tbl_job` VALUES ('680', 'ผู้ปฏิบัติงานด้านการประกอบอื่นๆ นอกเหนือจากชิ้นส่วนอิเล็กทรอนิกส์ ไฟฟ้าและเครื่องจักรกล');
INSERT INTO `tbl_job` VALUES ('681', 'ผู้ขับหัวรถจักร');
INSERT INTO `tbl_job` VALUES ('682', 'พนักงานขับรถไฟฟ้า');
INSERT INTO `tbl_job` VALUES ('683', 'พนักงานขับรถไฟ');
INSERT INTO `tbl_job` VALUES ('684', 'พนักงานห้ามล้อรถไฟ พนักงานส่งสัญญาณรถไฟ และพนักงานสับเปลี่ยนรถไฟ');
INSERT INTO `tbl_job` VALUES ('685', 'ผู้ขับขี่รถจักรยานยนต์');
INSERT INTO `tbl_job` VALUES ('686', 'คนขับขี่รถจักรยานยนต์ส่งเอกสาร/สินค้า');
INSERT INTO `tbl_job` VALUES ('687', 'คนขับขี่รถสามล้อเครื่อง');
INSERT INTO `tbl_job` VALUES ('688', 'ผู้ขับขี่รถยนต์ รถแท็กซี่ และรถตู้');
INSERT INTO `tbl_job` VALUES ('689', 'ผู้ขับรถโดยสารและรถราง');
INSERT INTO `tbl_job` VALUES ('690', 'ผู้ขับรถโดยสารประจำทาง');
INSERT INTO `tbl_job` VALUES ('691', 'ผู้ขับรถบรรทุกขนาดใหญ่');
INSERT INTO `tbl_job` VALUES ('692', 'คนขับรถพ่วง');
INSERT INTO `tbl_job` VALUES ('693', 'คนขับรถขยะ');
INSERT INTO `tbl_job` VALUES ('694', 'ผู้ควบคุมเครื่องจักรโรงงานชนิดเคลื่อนที่ได้ที่ใช้ในด้านการเกษตรและป่าไม้');
INSERT INTO `tbl_job` VALUES ('695', 'คนขับรถแทรกเตอร์');
INSERT INTO `tbl_job` VALUES ('696', 'ผู้ควบคุมเครื่องจักรขนย้ายดินและหิน และเครื่องจักรโรงงานที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('697', 'พนักงานขับรถบดถนน');
INSERT INTO `tbl_job` VALUES ('698', 'พนักงานขับรถแทรกเตอร์เกลี่ยดิน');
INSERT INTO `tbl_job` VALUES ('699', 'พนักงานขับรถปรับดิน/บลูโดเซอร์');
INSERT INTO `tbl_job` VALUES ('700', 'พนักงานรถขุดดิน');
INSERT INTO `tbl_job` VALUES ('701', 'ผู้ควบคุมปั้นจั่น รอกยก และเครื่องจักรโรงงานที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('702', 'ผู้ควบคุมรถยกสินค้า');
INSERT INTO `tbl_job` VALUES ('703', 'คนขับรถยก');
INSERT INTO `tbl_job` VALUES ('704', 'ลูกเรือบนเรือและผู้ปฏิบัติงานอื่นๆที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('705', 'กลาสีเรือ');
INSERT INTO `tbl_job` VALUES ('706', 'คนงานและผู้ช่วยทำความสะอาดที่พักอาศัย');
INSERT INTO `tbl_job` VALUES ('707', 'คนทำงานบ้านทั่วไป');
INSERT INTO `tbl_job` VALUES ('708', 'คนงานและผู้ช่วยทำความสะอาดสำนักงาน โรงแรม และสถานประกอบการอื่นๆ');
INSERT INTO `tbl_job` VALUES ('709', 'คนงานซักรีดเสื้อผ้าด้วยมือ');
INSERT INTO `tbl_job` VALUES ('710', 'คนงานทำความสะอาดยานพาหนะ');
INSERT INTO `tbl_job` VALUES ('711', 'คนงานทำความสะอาดหน้าต่าง');
INSERT INTO `tbl_job` VALUES ('712', 'คนงานทำความสะอาดอื่นๆ');
INSERT INTO `tbl_job` VALUES ('713', 'คนงาน ทำความสะอาดสระว่ายน้ำ');
INSERT INTO `tbl_job` VALUES ('714', 'คนงานปลูกพืชไร่/พืชผัก');
INSERT INTO `tbl_job` VALUES ('715', 'คนงานเลี้ยงสัตว์');
INSERT INTO `tbl_job` VALUES ('716', 'คนต้อนฝูงสัตว์');
INSERT INTO `tbl_job` VALUES ('717', 'คนเก็บฟืน');
INSERT INTO `tbl_job` VALUES ('718', 'คนตักน้ำ');
INSERT INTO `tbl_job` VALUES ('719', 'คนงานปลูกพืชร่วมกับเลี้ยงสัตว์');
INSERT INTO `tbl_job` VALUES ('720', 'คนงานปลูกพืชสวนและไม้ดอกไม้ประดับ');
INSERT INTO `tbl_job` VALUES ('721', 'คนงานตัดหญ้าสนาม');
INSERT INTO `tbl_job` VALUES ('722', 'คนงานเพาะชำพันธุ์ไม้');
INSERT INTO `tbl_job` VALUES ('723', 'คนงานป่าไม้');
INSERT INTO `tbl_job` VALUES ('724', 'คนงานประมงและเพาะเลี้ยงสัตว์น้ำ');
INSERT INTO `tbl_job` VALUES ('725', 'คนงานเหมืองแร่และเหมืองหิน');
INSERT INTO `tbl_job` VALUES ('726', 'คนทดสอบตัวอย่างหิน');
INSERT INTO `tbl_job` VALUES ('727', 'คนงานก่อสร้างและบำรุงรักษาถนน เขื่อน และงานวิศวกรรมโยธาอื่นๆ ที่คล้ายกัน');
INSERT INTO `tbl_job` VALUES ('728', 'คนงานขนดิน');
INSERT INTO `tbl_job` VALUES ('729', 'คนงานก่อสร้างอาคาร สิ่งปลูกสร้าง');
INSERT INTO `tbl_job` VALUES ('730', 'คนงานรื้อถอนอาคาร/สิ่งปลูกสร้าง');
INSERT INTO `tbl_job` VALUES ('731', 'คนงานแบกของในสถานที่ก่อสร้าง');
INSERT INTO `tbl_job` VALUES ('732', 'คนงานบรรจุผลิตภัณฑ์ด้วยมือ');
INSERT INTO `tbl_job` VALUES ('733', 'คนงานติดฉลากผลิตภัณฑ์ด้วยมือ');
INSERT INTO `tbl_job` VALUES ('734', 'คนงานห่อผลิตภัณฑ์ด้วยมือ');
INSERT INTO `tbl_job` VALUES ('735', 'คนงานด้านการผลิต ซึ่งมิได้จัดประเภทไว้ในที่อื่น');
INSERT INTO `tbl_job` VALUES ('736', 'คนงานขับเคลื่อนยานพาหนะโดยใช้มือหรือเท้า');
INSERT INTO `tbl_job` VALUES ('737', 'คนถีบสามล้อ');
INSERT INTO `tbl_job` VALUES ('738', 'คนเข็นของ');
INSERT INTO `tbl_job` VALUES ('739', 'คนงานขับเคลื่อนยานพาหนะและเครื่องจักรต่างๆ ที่ลากจูงโดยสัตว์');
INSERT INTO `tbl_job` VALUES ('740', 'ควาญช้าง');
INSERT INTO `tbl_job` VALUES ('741', 'คนงานขนถ่ายสินค้า');
INSERT INTO `tbl_job` VALUES ('742', 'คนงานเติมสินค้าบนชั้นวาง');
INSERT INTO `tbl_job` VALUES ('743', 'ผู้ประกอบอาหารจานด่วน');
INSERT INTO `tbl_job` VALUES ('744', 'ผู้ช่วยงานครัว');
INSERT INTO `tbl_job` VALUES ('745', 'เจ้าหน้าที่โรงครัว');
INSERT INTO `tbl_job` VALUES ('746', 'ผู้ให้บริการตามถนนและสถานที่ที่คล้ายกัน');
INSERT INTO `tbl_job` VALUES ('747', 'คนเฝ้ารถยนต์/รับฝากรถยนต์');
INSERT INTO `tbl_job` VALUES ('748', 'ผู้จำหน่ายสินค้าตามถนน (ยกเว้นอาหารพร้อมบริโภค)');
INSERT INTO `tbl_job` VALUES ('749', 'คนหาบของเร่ขาย');
INSERT INTO `tbl_job` VALUES ('750', 'คนเร่ขายของ');
INSERT INTO `tbl_job` VALUES ('751', 'คนขายหนังสือพิมพ์ตามถนน');
INSERT INTO `tbl_job` VALUES ('752', 'คนเก็บขยะและวัสดุที่สามารถนำกลับมาใช้ใหม่');
INSERT INTO `tbl_job` VALUES ('753', 'คนงานเก็บขยะ');
INSERT INTO `tbl_job` VALUES ('754', 'คนงานคัดแยกขยะ');
INSERT INTO `tbl_job` VALUES ('755', 'คนเก็บขยะหรือของเก่าขาย');
INSERT INTO `tbl_job` VALUES ('756', 'คนขายขยะรีไซเคิล');
INSERT INTO `tbl_job` VALUES ('757', 'คนกวาดถนนและผู้ใช้แรงงานที่เกี่ยวข้อง');
INSERT INTO `tbl_job` VALUES ('758', 'คนกวาดสวนสาธารณะ');
INSERT INTO `tbl_job` VALUES ('759', 'คนกวาดขยะ');
INSERT INTO `tbl_job` VALUES ('760', 'พนักงานรับส่งข่าวสาร หีบห่อสิ่งของและสัมภาระ');
INSERT INTO `tbl_job` VALUES ('761', 'คนส่งหนังสือพิมพ์');
INSERT INTO `tbl_job` VALUES ('762', 'พนักงานยกกระเป๋าโรงแรม');
INSERT INTO `tbl_job` VALUES ('763', 'คนส่งหนังสือพิมพ์');
INSERT INTO `tbl_job` VALUES ('764', 'คนเดินเอกสาร');
INSERT INTO `tbl_job` VALUES ('765', 'คนงานรับจ้างทั่วไป');
INSERT INTO `tbl_job` VALUES ('766', 'คนจดมาตรวัดและเก็บเงินจากเครื่องจำหน่ายสินค้าอัตโนมัติ');
INSERT INTO `tbl_job` VALUES ('767', 'คนตักน้ำและเก็บฟืน');
INSERT INTO `tbl_job` VALUES ('768', 'ผู้ประกอบวิชาชีพงานพื้นฐานอื่นๆ ซึ่งมิได้จัดประเภทไว้ที่อื่น');
INSERT INTO `tbl_job` VALUES ('769', 'พนักงานประจำลานจอดรถ');
INSERT INTO `tbl_job` VALUES ('770', 'นักเรียน/นักศึกษา');
INSERT INTO `tbl_job` VALUES ('771', 'แม่บ้าน/พ่อบ้าน');
INSERT INTO `tbl_job` VALUES ('772', 'ในปกครอง');
INSERT INTO `tbl_job` VALUES ('773', 'ข้าราชการบำนาญ');
INSERT INTO `tbl_job` VALUES ('774', 'ลูกจ้างประจำ');
INSERT INTO `tbl_job` VALUES ('775', 'ลูกจ้างชั่วคราว');
INSERT INTO `tbl_job` VALUES ('776', 'ไม่มีงานทำ');
